import { afterEach, describe, it, expect, vi } from 'vitest';
import { parseMrUrl, formatComment, postOrUpdateMrComment } from '../ci/mr-comment.js';
import type { LearningDraft, CodebaseSuggestion } from '../types.js';

describe('parseMrUrl', () => {
  it('解析 GitHub PR URL', () => {
    const result = parseMrUrl('https://github.com/owner/repo/pull/42');
    expect(result).toEqual({ provider: 'github', owner: 'owner', repo: 'repo', number: '42' });
  });

  it('解析 TGit MR URL（单层 group）', () => {
    const result = parseMrUrl('https://git.woa.com/team/project/merge_requests/7');
    expect(result).toEqual({ provider: 'tgit', owner: 'team', repo: 'project', number: '7' });
  });

  it('解析 TGit MR URL（多层 group）', () => {
    const result = parseMrUrl('https://git.woa.com/group/sub/project/merge_requests/123');
    expect(result).toEqual({ provider: 'tgit', owner: 'group/sub', repo: 'project', number: '123' });
  });

  it('不支持的 URL 抛出错误', () => {
    expect(() => parseMrUrl('https://gitlab.com/org/repo/-/merge_requests/1')).toThrow('无法解析 MR URL');
  });
});

describe('formatComment', () => {
  const marker = '<!-- teamai:ci-extract -->';

  it('格式化含 learning 和 suggestions 的 comment', () => {
    const learning: LearningDraft = {
      title: '修复数据库连接泄漏',
      content: '---\ntitle: 修复数据库连接泄漏\n---\n\n## 背景\n连接未关闭',
    };
    const suggestions: CodebaseSuggestion[] = [
      { section: '架构', action: 'update', content: '新增连接池管理模块' },
    ];

    const result = formatComment(learning, suggestions, marker);

    expect(result).toContain(marker);
    expect(result).toContain('修复数据库连接泄漏');
    expect(result).toContain('### Learning');
    expect(result).toContain('### Codebase.md 更新建议');
    expect(result).toContain('| 架构 | update |');
    expect(result).toContain('Auto-generated by');
  });

  it('无 learning 和 suggestions 时显示"无可提炼"', () => {
    const result = formatComment(undefined, undefined, marker);
    expect(result).toContain(marker);
    expect(result).toContain('无可提炼的知识内容');
    expect(result).not.toContain('### Learning');
  });

  it('仅有 learning 无 suggestions', () => {
    const learning: LearningDraft = {
      title: '测试标题',
      content: '内容',
    };
    const result = formatComment(learning, [], marker);
    expect(result).toContain('### Learning');
    expect(result).not.toContain('### Codebase.md 更新建议');
  });
});

describe('postOrUpdateMrComment API failures', () => {
  afterEach(() => {
    vi.unstubAllEnvs();
    vi.unstubAllGlobals();
  });

  it('fails without creating a duplicate GitHub comment when listing comments fails', async () => {
    vi.stubEnv('GITHUB_TOKEN', 'test-token');
    const fetchMock = vi.fn().mockResolvedValue(new Response(null, { status: 503 }));
    vi.stubGlobal('fetch', fetchMock);

    await expect(postOrUpdateMrComment(
      'https://github.com/acme/app/pull/7', undefined, undefined,
    )).rejects.toThrow('GitHub comment list request failed (503)');

    expect(fetchMock).toHaveBeenCalledTimes(1);
    expect(fetchMock.mock.calls[0][1]?.method).toBe('GET');
  });

  it('fails without creating a duplicate TGit note when listing notes fails', async () => {
    vi.stubEnv('TGIT_TOKEN', 'test-token');
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(new Response(JSON.stringify([{ id: 42, iid: 7 }]), { status: 200 }))
      .mockResolvedValueOnce(new Response(null, { status: 503 }));
    vi.stubGlobal('fetch', fetchMock);

    await expect(postOrUpdateMrComment(
      'https://git.woa.com/acme/app/merge_requests/7', undefined, undefined,
    )).rejects.toThrow('TGit note list request failed (503)');

    expect(fetchMock).toHaveBeenCalledTimes(2);
    expect(fetchMock.mock.calls.some(([, init]) => init?.method === 'POST')).toBe(false);
  });
});
