import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import path from 'node:path';
import os from 'node:os';
import fse from 'fs-extra';
import { fileURLToPath } from 'node:url';
import { shipped, shippedSkillDigestsMock } from './helpers/shipped-skills.js';

const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

// ─── Mocks ─────────────────────────────────────────────

// A CLI-owned file is one whose content a release shipped; `shipped()` is it here.
vi.mock('../packaged-skill-digests.js', () => shippedSkillDigestsMock());

const mockAutoDetectInit = vi.fn();
const mockSaveLocalConfig = vi.fn();
const mockSaveLocalConfigForScope = vi.fn();

vi.mock('../config.js', async (importOriginal) => ({
  ...(await importOriginal<typeof import('../config.js')>()),
  autoDetectInit: (...args: unknown[]) => mockAutoDetectInit(...args),
  saveLocalConfig: (...args: unknown[]) => mockSaveLocalConfig(...args),
  saveLocalConfigForScope: (...args: unknown[]) => mockSaveLocalConfigForScope(...args),
}));

const mockReconcileHooks = vi.fn();

vi.mock('../hooks.js', async (importOriginal) => {
  const actual = await importOriginal<typeof import('../hooks.js')>();
  return { ...actual, reconcileHooks: (...args: unknown[]) => mockReconcileHooks(...args) };
});

vi.mock('../utils/logger.js', () => ({
  log: {
    info: vi.fn(),
    success: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
    debug: vi.fn(),
    dim: vi.fn(),
  },
  spinner: vi.fn(() => ({
    start: vi.fn().mockReturnThis(),
    succeed: vi.fn().mockReturnThis(),
    fail: vi.fn().mockReturnThis(),
  })),
}));

import { uninstall } from '../uninstall.js';
import { EnvHandler } from '../resources/env.js';
import { TeamaiConfigSchema } from '../types.js';
import { ModelProfileSchema, resolveProfile } from '../models/profile.js';
import { switchModelProfile } from '../models/switch.js';
import type { TeamaiConfig, LocalConfig } from '../types.js';

// ─── Helpers ───────────────────────────────────────────

const TEAMAI_RULES_START = '<!-- [teamai:rules:start] -->';
const TEAMAI_RULES_END = '<!-- [teamai:rules:end] -->';
const TEAMAI_CULTURE_START = '<!-- [teamai:culture:start] -->';
const TEAMAI_CULTURE_END = '<!-- [teamai:culture:end] -->';
const TEAMAI_CLAUDEMD_START = '<!-- [teamai:claudemd:start] -->';
const TEAMAI_CLAUDEMD_END = '<!-- [teamai:claudemd:end] -->';
const TEAMAI_RECALL_RULES_START = '<!-- [teamai:recall-rules:start] -->';
const TEAMAI_RECALL_RULES_END = '<!-- [teamai:recall-rules:end] -->';
const TEAMAI_ENV_START = '# [teamai:env:start]';
const TEAMAI_ENV_END = '# [teamai:env:end]';
const TEAMAI_PI_HOOK = '// [teamai] hooks extension — generated by teamai';

function makeTeamConfig(overrides?: Partial<TeamaiConfig>): TeamaiConfig {
  return {
    team: 'test',
    description: '',
    repo: 'https://git.woa.com/test/repo.git',
    provider: 'tgit' as const,
    reviewers: [],
    sharing: {
      skills: {},
      rules: { enforced: [] },
      docs: { localDir: '~/.teamai/docs' },
      env: { injectShellProfile: true },
    },
    toolPaths: {
      claude: {
        skills: '.claude/skills',
        rules: '.claude/rules',
        settings: '.claude/settings.json',
        claudemd: '.claude/CLAUDE.md',
        agents: '.claude/agents',
      },
    },
    ...overrides,
  };
}

function makeLocalConfig(homeDir: string, repoPath: string, overrides?: Partial<LocalConfig>): LocalConfig {
  return {
    repo: { localPath: repoPath, remote: 'https://git.woa.com/test/repo.git' },
    username: 'testuser',
    updatePolicy: 'auto',
    scope: 'user',
    additionalRoles: [],
    ...overrides,
  };
}

async function setupFixture(tmpDir: string) {
  const homeDir = path.join(tmpDir, 'home');
  const repoPath = path.join(tmpDir, 'team-repo');
  const teamaiHome = path.join(homeDir, '.teamai');

  // Team repo: skills
  await fse.ensureDir(path.join(repoPath, 'skills', 'team-skill'));
  await fse.writeFile(path.join(repoPath, 'skills', 'team-skill', 'SKILL.md'), '# Team Skill');

  // Team repo: rules
  await fse.ensureDir(path.join(repoPath, 'rules'));
  await fse.writeFile(path.join(repoPath, 'rules', 'team-rule.md'), '# Team Rule');

  // Tool dirs: synced skill + user skill
  await fse.ensureDir(path.join(homeDir, '.claude', 'skills', 'team-skill'));
  await fse.writeFile(path.join(homeDir, '.claude', 'skills', 'team-skill', 'SKILL.md'), '# Team Skill');
  await fse.ensureDir(path.join(homeDir, '.claude', 'skills', 'my-own-skill'));
  await fse.writeFile(path.join(homeDir, '.claude', 'skills', 'my-own-skill', 'SKILL.md'), '# My Skill');

  // Tool dirs: synced rule
  await fse.ensureDir(path.join(homeDir, '.claude', 'rules'));
  await fse.writeFile(path.join(homeDir, '.claude', 'rules', 'team-rule.md'), '# Team Rule');

  // Tool dirs: CLI built-in resources (deployed by the CLI, not the team repo)
  await fse.writeFile(path.join(homeDir, '.claude', 'rules', 'teamai-recall.md'), '# Recall Rule');
  await fse.ensureDir(path.join(homeDir, '.claude', 'agents'));
  await fse.writeFile(path.join(homeDir, '.claude', 'agents', 'teamai-recall.md'), '# Recall Agent');
  await fse.ensureDir(path.join(homeDir, '.claude', 'skills', 'teamai'));
  await fse.writeFile(path.join(homeDir, '.claude', 'skills', 'teamai', 'SKILL.md'), shipped('teamai', 'SKILL.md'));
  await fse.ensureDir(path.join(homeDir, '.claude', 'skills', 'teamai-share-learnings'));
  await fse.writeFile(path.join(homeDir, '.claude', 'skills', 'teamai-share-learnings', 'SKILL.md'), shipped('teamai-share-learnings', 'SKILL.md'));
  await fse.ensureDir(path.join(homeDir, '.claude', 'skills', 'team-wiki-codebase'));
  await fse.writeFile(path.join(homeDir, '.claude', 'skills', 'team-wiki-codebase', 'SKILL.md'), shipped('team-wiki-codebase', 'SKILL.md'));

  // Settings.json with hooks
  await fse.writeJson(path.join(homeDir, '.claude', 'settings.json'), {
    hooks: { SessionStart: [{ matcher: '*', hooks: [{ type: 'command', command: 'teamai pull' }], description: '[teamai] Auto-pull' }] },
  });

  // CLAUDE.md with all teamai section blocks + user content
  const claudeMd = [
    '# My custom instructions',
    '',
    TEAMAI_RULES_START,
    '<!-- DO NOT EDIT -->',
    '## Team Rules (teamai)',
    TEAMAI_RULES_END,
    '',
    TEAMAI_CULTURE_START,
    '## Team Culture',
    'We value collaboration.',
    TEAMAI_CULTURE_END,
    '',
    TEAMAI_CLAUDEMD_START,
    '## Shared Instructions',
    'Always use TypeScript.',
    TEAMAI_CLAUDEMD_END,
    '',
    TEAMAI_RECALL_RULES_START,
    '## Recall Rules',
    'Use teamai-recall subagent.',
    TEAMAI_RECALL_RULES_END,
    '',
  ].join('\n');
  await fse.writeFile(path.join(homeDir, '.claude', 'CLAUDE.md'), claudeMd);

  // Shell profile with env block. The source line points at this scope's own
  // env.sh (not a `~` shorthand) since uninstall now only cleans a block that
  // sources the current scope's data home (#693 review).
  const envShPosix = path.join(homeDir, '.teamai', 'env.sh').split(path.sep).join('/');
  const zshrc = [
    '# My zshrc config',
    'export PATH=$HOME/bin:$PATH',
    '',
    TEAMAI_ENV_START,
    '# DO NOT EDIT',
    `[ -f '${envShPosix}' ] && source '${envShPosix}'`,
    TEAMAI_ENV_END,
    '',
    '# More user config',
  ].join('\n');
  await fse.writeFile(path.join(homeDir, '.zshrc'), zshrc);

  // ~/.teamai/ directory
  await fse.ensureDir(path.join(teamaiHome, 'docs'));
  await fse.writeFile(path.join(teamaiHome, 'docs', 'guide.md'), '# Guide');
  await fse.writeFile(path.join(teamaiHome, 'config.yaml'), 'repo: test');
  await fse.writeFile(path.join(teamaiHome, 'state.json'), '{}');
  await fse.writeFile(path.join(teamaiHome, 'usage.jsonl'), '');

  return { homeDir, repoPath, teamaiHome };
}

// ─── Tests ─────────────────────────────────────────────

describe('uninstall', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fse.mkdtemp(path.join(os.tmpdir(), 'teamai-uninstall-test-'));
    vi.stubEnv('CLAUDE_CONFIG_DIR', undefined);
    mockAutoDetectInit.mockReset();
    mockReconcileHooks.mockReset();
    mockSaveLocalConfig.mockReset();
    mockSaveLocalConfigForScope.mockReset();
    // These tests exercise the SHELL-based POSIX branch of detectShellProfile
    // via stubbed SHELL values; pin the platform so they assert the same
    // thing on a Windows dev machine as they do in CI (ubuntu/macos). The
    // win32 branch has its own tests in shell-profile.test.ts.
    vi.spyOn(process, 'platform', 'get').mockReturnValue('linux');
  });

  afterEach(async () => {
    vi.unstubAllEnvs();
    vi.restoreAllMocks();
    await fse.remove(tmpDir);
  });

  it('完整卸载移除所有资源', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const teamConfig = makeTeamConfig({
      sharing: {
        skills: {},
        rules: { enforced: [] },
        docs: { localDir: `${teamaiHome}/docs` },
        env: { injectShellProfile: true },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    // hooks: reconcileHooks(removeAll) was called for the tool settings file,
    // with the managed-hooks manifest so team (B) hooks are cleaned up too.
    expect(mockReconcileHooks).toHaveBeenCalledWith(
      path.join(homeDir, '.claude', 'settings.json'),
      'claude',
      [],
      expect.objectContaining({ removeAll: true, manifestPath: expect.stringContaining('managed-hooks.json') }),
    );

    // CLAUDE.md: teamai block removed, user content preserved
    const claudeMd = await fse.readFile(path.join(homeDir, '.claude', 'CLAUDE.md'), 'utf-8');
    expect(claudeMd).toContain('# My custom instructions');
    expect(claudeMd).not.toContain(TEAMAI_RULES_START);

    // Synced skill removed, user skill preserved
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'team-skill'))).toBe(false);
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'my-own-skill'))).toBe(true);

    // Synced rule removed
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'rules', 'team-rule.md'))).toBe(false);

    // Shell profile: env block removed, user content preserved
    const zshrc = await fse.readFile(path.join(homeDir, '.zshrc'), 'utf-8');
    expect(zshrc).toContain('export PATH=$HOME/bin:$PATH');
    expect(zshrc).toContain('# More user config');
    expect(zshrc).not.toContain(TEAMAI_ENV_START);

    // ~/.teamai/ removed
    expect(await fse.pathExists(teamaiHome)).toBe(false);
  });

  // Regression (#693 review): the Windows fix in #682 changed which profile
  // file `pull` prefers, so a machine last pulled with an older CLI can carry
  // a stale env block in a file the current detectShellProfile() resolution
  // no longer points at (a fresh pull then adds a second block elsewhere).
  // uninstall must find and clean every such file, not only the current one.
  it('cleans a stale env block left in an old profile file alongside the current one', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '');
    vi.spyOn(process, 'platform', 'get').mockReturnValue('win32');

    // Both blocks source THIS scope's own env.sh — only their file location
    // differs, exactly like an upgrade across #682 would leave things.
    const envShPosix = path.join(homeDir, '.teamai', 'env.sh').split(path.sep).join('/');

    // Stale block: what an older CLI wrote to .bashrc before #682.
    const staleBashrc = [
      '# my bashrc',
      TEAMAI_ENV_START,
      '# DO NOT EDIT',
      `[ -f '${envShPosix}' ] && source '${envShPosix}'`,
      TEAMAI_ENV_END,
    ].join('\n');
    await fse.writeFile(path.join(homeDir, '.bashrc'), staleBashrc);

    // Current block: what the fixed CLI writes to .profile today.
    const currentProfile = [
      '# my profile',
      TEAMAI_ENV_START,
      '# DO NOT EDIT',
      `[ -f '${envShPosix}' ] && source '${envShPosix}'`,
      TEAMAI_ENV_END,
    ].join('\n');
    await fse.writeFile(path.join(homeDir, '.profile'), currentProfile);

    const teamConfig = makeTeamConfig({
      sharing: {
        skills: {},
        rules: { enforced: [] },
        docs: { localDir: `${teamaiHome}/docs` },
        env: { injectShellProfile: true },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    const bashrc = await fse.readFile(path.join(homeDir, '.bashrc'), 'utf-8');
    expect(bashrc).toContain('# my bashrc');
    expect(bashrc).not.toContain(TEAMAI_ENV_START);

    const profile = await fse.readFile(path.join(homeDir, '.profile'), 'utf-8');
    expect(profile).toContain('# my profile');
    expect(profile).not.toContain(TEAMAI_ENV_START);
  });

  // Regression (#693 review): scanning every candidate filename must not
  // delete a DIFFERENT scope's still-active block just because it also
  // happens to carry the teamai marker — only a block sourcing THIS scope's
  // own env.sh may be touched.
  it('leaves another scope\'s env block untouched even though it shares a candidate filename', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '');
    vi.spyOn(process, 'platform', 'get').mockReturnValue('win32');

    // A project scope's block, unrelated to the user-scope uninstall below.
    const otherProjectEnvSh = path.join(tmpDir, 'other-project', '.teamai', 'env.sh')
      .split(path.sep).join('/');
    const bashrc = [
      '# my bashrc',
      TEAMAI_ENV_START,
      '# DO NOT EDIT',
      `[ -f '${otherProjectEnvSh}' ] && source '${otherProjectEnvSh}'`,
      TEAMAI_ENV_END,
    ].join('\n');
    await fse.writeFile(path.join(homeDir, '.bashrc'), bashrc);

    const teamConfig = makeTeamConfig({
      sharing: {
        skills: {},
        rules: { enforced: [] },
        docs: { localDir: `${teamaiHome}/docs` },
        env: { injectShellProfile: true },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath); // scope: 'user'
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    // The unrelated project-scope block must survive intact.
    const bashrcAfter = await fse.readFile(path.join(homeDir, '.bashrc'), 'utf-8');
    expect(bashrcAfter).toBe(bashrc);
  });

  // #876: a user-scope block and a project-scope block share ~/.zshrc.
  // Uninstalling either scope removes its own block and leaves the other one
  // exactly as it was, wherever each sits in the file.
  describe('with a user-scope and a project-scope block in one profile', () => {
    const scopeBlock = (envSh: string): string => new EnvHandler().generateShellBlock(path.dirname(envSh));

    async function setupTwoBlocks() {
      const fixture = await setupFixture(tmpDir);
      vi.stubEnv('HOME', fixture.homeDir);
      vi.stubEnv('SHELL', '/bin/zsh');
      const projectRoot = path.join(tmpDir, 'work', 'api');
      const userBlock = scopeBlock(path.join(fixture.teamaiHome, 'env.sh'));
      const projectBlock = scopeBlock(path.join(projectRoot, '.teamai', 'env.sh'));
      await fse.writeFile(
        path.join(fixture.homeDir, '.zshrc'),
        ['# My zshrc config', '', userBlock, '', projectBlock, '', '# More user config'].join('\n'),
      );
      return { ...fixture, projectRoot, userBlock, projectBlock };
    }

    it('project uninstall removes only the project block', async () => {
      const { homeDir, projectRoot, userBlock, projectBlock } = await setupTwoBlocks();
      const localConfig = makeLocalConfig(projectRoot, path.join(projectRoot, '.teamai', 'team-repo'), {
        scope: 'project',
        projectRoot,
      });
      mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig: makeTeamConfig() });

      await uninstall({ force: true });

      const zshrc = await fse.readFile(path.join(homeDir, '.zshrc'), 'utf-8');
      expect(zshrc).toContain(userBlock);
      expect(zshrc).not.toContain(projectBlock);
      expect(zshrc).toContain('# More user config');
    });

    it('user uninstall removes only the user block', async () => {
      const { homeDir, repoPath, teamaiHome, userBlock, projectBlock } = await setupTwoBlocks();
      const teamConfig = makeTeamConfig({
        sharing: {
          skills: {},
          rules: { enforced: [] },
          docs: { localDir: `${teamaiHome}/docs` },
          env: { injectShellProfile: true },
        },
      });
      mockAutoDetectInit.mockResolvedValue({ localConfig: makeLocalConfig(homeDir, repoPath), teamConfig });

      await uninstall({ force: true });

      const zshrc = await fse.readFile(path.join(homeDir, '.zshrc'), 'utf-8');
      expect(zshrc).toContain(projectBlock);
      expect(zshrc).not.toContain(userBlock);
      expect(zshrc).toContain('# My zshrc config');
    });
  });

  // Regression (#693 hardware review by @CarlosWonMore): a pre-#661 CLI wrote
  // the source path raw and unquoted, with unconverted backslashes. That
  // block is broken (a POSIX shell never loads it) but still names this
  // scope's own env.sh, and uninstall must still find and remove it — not
  // just blocks written in the current quoted/forward-slash format.
  it('cleans a pre-#661 legacy block (raw, unquoted, unconverted backslashes)', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '');
    vi.spyOn(process, 'platform', 'get').mockReturnValue('win32');

    const envShWindows = path.join(homeDir, '.teamai', 'env.sh');
    const legacyBashrc = [
      '# my bashrc',
      TEAMAI_ENV_START,
      '# DO NOT EDIT',
      `[ -f ${envShWindows} ] && source ${envShWindows}`,
      TEAMAI_ENV_END,
    ].join('\n');
    await fse.writeFile(path.join(homeDir, '.bashrc'), legacyBashrc);
    await fse.writeFile(path.join(homeDir, '.profile'), '# my profile');

    const teamConfig = makeTeamConfig({
      sharing: {
        skills: {},
        rules: { enforced: [] },
        docs: { localDir: `${teamaiHome}/docs` },
        env: { injectShellProfile: true },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    const bashrcAfter = await fse.readFile(path.join(homeDir, '.bashrc'), 'utf-8');
    expect(bashrcAfter).toContain('# my bashrc');
    expect(bashrcAfter).not.toContain(TEAMAI_ENV_START);
  });

  it('project-scope Pi uninstall also removes the global extension', async () => {
    // Mirrors OMP: Pi has no way to scope its single shared extension to one
    // project — the generated extension fires for every Pi session
    // machine-wide — so a scoped uninstall removes it outright rather than
    // preserving a file that would keep firing for this project anyway.
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    const projectRoot = path.join(tmpDir, 'business-repo');
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const globalPiHook = path.join(homeDir, '.pi', 'agent', 'extensions', 'teamai-hooks.ts');
    const projectPiHook = path.join(projectRoot, '.pi', 'extensions', 'teamai-hooks.ts');
    await fse.ensureDir(path.dirname(globalPiHook));
    await fse.ensureDir(path.dirname(projectPiHook));
    await fse.writeFile(globalPiHook, TEAMAI_PI_HOOK);
    await fse.writeFile(projectPiHook, TEAMAI_PI_HOOK);

    const teamConfig = makeTeamConfig({
      toolPaths: {
        pi: {
          skills: '.pi/skills',
          rules: '.pi/rules',
          claudemd: 'AGENTS.md',
          userScope: {
            skills: '.pi/agent/skills',
            rules: '.pi/agent/rules',
            claudemd: '.pi/agent/AGENTS.md',
          },
        },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath, {
      scope: 'project',
      projectRoot,
      repo: { localPath: repoPath, remote: '', kind: 'self', businessRepoRoot: projectRoot },
    });
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'pi' });

    expect(await fse.pathExists(projectPiHook)).toBe(false);
    expect(await fse.pathExists(globalPiHook)).toBe(false);
  });

  it('user-scope Pi uninstall removes a server-pushed agent hook even without the main extension', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    // No teamai-hooks.ts here — only an HTTP-source agent hook, mirroring a
    // user who only ever got a server-pushed hook and never the lifecycle
    // bridge (or removed it by hand).
    const agentHookFile = path.join(homeDir, '.pi', 'agent', 'extensions', 'teamai-agent-scan.ts');
    await fse.ensureDir(path.dirname(agentHookFile));
    await fse.writeFile(agentHookFile, '// [teamai] agent hook [scan] — generated by teamai, do not edit by hand.');

    const teamConfig = makeTeamConfig({
      toolPaths: { pi: { skills: '.pi/skills', rules: '.pi/rules', claudemd: 'AGENTS.md' } },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'pi' });

    expect(await fse.pathExists(agentHookFile)).toBe(false);
  });

  it('does not delete a same-named agent-hook file without the TeamAI marker', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const agentHookFile = path.join(homeDir, '.pi', 'agent', 'extensions', 'teamai-agent-scan.ts');
    await fse.ensureDir(path.dirname(agentHookFile));
    await fse.writeFile(agentHookFile, '// user-owned extension');

    const teamConfig = makeTeamConfig({
      toolPaths: { pi: { skills: '.pi/skills', rules: '.pi/rules', claudemd: 'AGENTS.md' } },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'pi' });

    expect(await fse.readFile(agentHookFile, 'utf8')).toBe('// user-owned extension');
  });

  it('does not delete a same-named project Pi extension without the TeamAI marker', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    const projectRoot = path.join(tmpDir, 'business-repo');
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const projectPiHook = path.join(projectRoot, '.pi', 'extensions', 'teamai-hooks.ts');
    await fse.ensureDir(path.dirname(projectPiHook));
    await fse.writeFile(projectPiHook, '// user-owned extension');

    const teamConfig = makeTeamConfig({
      toolPaths: { pi: { skills: '.pi/skills', rules: '.pi/rules', claudemd: 'AGENTS.md' } },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath, {
      scope: 'project',
      projectRoot,
      repo: { localPath: repoPath, remote: '', kind: 'self', businessRepoRoot: projectRoot },
    });
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'pi' });

    expect(await fse.readFile(projectPiHook, 'utf8')).toBe('// user-owned extension');
  });

  it('targeted Pi uninstall preserves a shared AGENTS.md used by another installed agent', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    const projectRoot = path.join(tmpDir, 'business-repo');
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const sharedInstructions = path.join(projectRoot, 'AGENTS.md');
    const projectPiHook = path.join(projectRoot, '.pi', 'extensions', 'teamai-hooks.ts');
    await fse.ensureDir(path.dirname(projectPiHook));
    // WorkBuddy is actually installed here (its own resource dir exists),
    // not just present in toolPaths — see the sibling "not installed" test.
    await fse.ensureDir(path.join(projectRoot, '.workbuddy', 'skills'));
    await fse.writeFile(sharedInstructions, `${TEAMAI_RULES_START}\nteam rules\n${TEAMAI_RULES_END}\n`);
    await fse.writeFile(projectPiHook, TEAMAI_PI_HOOK);

    const teamConfig = makeTeamConfig({
      toolPaths: {
        pi: {
          skills: '.pi/skills',
          rules: '.pi/rules',
          claudemd: 'AGENTS.md',
          userScope: {
            skills: '.pi/agent/skills',
            rules: '.pi/agent/rules',
            claudemd: '.pi/agent/AGENTS.md',
          },
        },
        workbuddy: {
          skills: '.workbuddy/skills',
          rules: '.workbuddy/rules',
          settings: '.workbuddy/settings.json',
          claudemd: 'AGENTS.md',
        },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath, {
      scope: 'project',
      projectRoot,
      enabledAgents: ['pi', 'workbuddy'],
      repo: { localPath: repoPath, remote: '', kind: 'self', businessRepoRoot: projectRoot },
    });
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'pi' });

    expect(await fse.pathExists(projectPiHook)).toBe(false);
    expect(await fse.pathExists(sharedInstructions)).toBe(true);
    expect(await fse.readFile(sharedInstructions, 'utf8')).toContain(TEAMAI_RULES_START);
  });

  it('targeted Pi uninstall removes shared AGENTS.md when the other tool sharing it was never installed', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    const projectRoot = path.join(tmpDir, 'business-repo');
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const sharedInstructions = path.join(projectRoot, 'AGENTS.md');
    const projectPiHook = path.join(projectRoot, '.pi', 'extensions', 'teamai-hooks.ts');
    await fse.ensureDir(path.dirname(projectPiHook));
    await fse.writeFile(sharedInstructions, `${TEAMAI_RULES_START}\nteam rules\n${TEAMAI_RULES_END}\n`);
    await fse.writeFile(projectPiHook, TEAMAI_PI_HOOK);
    // No .workbuddy directory is ever created — Hermes/WorkBuddy default to
    // the same project AGENTS.md as Pi in toolPaths, but neither is actually
    // set up here, so they must not block cleanup of Pi's shared instructions.

    const teamConfig = makeTeamConfig({
      toolPaths: {
        pi: { skills: '.pi/skills', rules: '.pi/rules', claudemd: 'AGENTS.md' },
        workbuddy: {
          skills: '.workbuddy/skills',
          rules: '.workbuddy/rules',
          settings: '.workbuddy/settings.json',
          claudemd: 'AGENTS.md',
        },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath, {
      scope: 'project',
      projectRoot,
      repo: { localPath: repoPath, remote: '', kind: 'self', businessRepoRoot: projectRoot },
    });
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'pi' });

    expect(await fse.pathExists(projectPiHook)).toBe(false);
    expect(await fse.pathExists(sharedInstructions)).toBe(false);
  });

  // Regression: Cursor rules are `.mdc`; matching only `.md` left every team
  // rule on disk after uninstall, still injected into each Cursor session.
  it('removes cursor .mdc rules (and a legacy .md copy) on uninstall', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const cursorRules = path.join(homeDir, '.cursor', 'rules');
    await fse.ensureDir(cursorRules);
    await fse.writeFile(path.join(cursorRules, 'team-rule.mdc'), '---\nalwaysApply: true\n---\n\n# Team Rule');
    // Left behind by the layout that predates `.mdc`.
    await fse.writeFile(path.join(cursorRules, 'team-rule.md'), '# Team Rule');
    // A rule the user wrote themselves must survive.
    await fse.writeFile(path.join(cursorRules, 'my-own-rule.mdc'), '---\nalwaysApply: true\n---\n\nmine');

    const teamConfig = makeTeamConfig({
      sharing: {
        skills: {},
        rules: { enforced: [] },
        docs: { localDir: `${teamaiHome}/docs` },
        env: { injectShellProfile: true },
      },
      toolPaths: {
        claude: {
          skills: '.claude/skills',
          rules: '.claude/rules',
          settings: '.claude/settings.json',
          claudemd: '.claude/CLAUDE.md',
          agents: '.claude/agents',
        },
        cursor: { skills: '.cursor/skills', rules: '.cursor/rules', settings: '.cursor/hooks.json' },
      },
    });
    mockAutoDetectInit.mockResolvedValue({ localConfig: makeLocalConfig(homeDir, repoPath), teamConfig });

    await uninstall({ force: true });

    expect(await fse.pathExists(path.join(cursorRules, 'team-rule.mdc'))).toBe(false);
    expect(await fse.pathExists(path.join(cursorRules, 'team-rule.md'))).toBe(false);
    expect(await fse.pathExists(path.join(cursorRules, 'my-own-rule.mdc'))).toBe(true);
  });

  // Regression: MCP cleanup used to run after ~/.teamai/ was deleted, so the
  // ownership manifest was already gone and removeAll became a no-op.
  it('卸载时移除 teamai 管理的 MCP server，并保留用户自建的', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    await fse.writeJson(path.join(homeDir, '.claude.json'), {
      mcpServers: {
        'team-mcp': { type: 'http', url: 'https://team.example/mcp' },
        'my-own': { command: 'my-server' },
      },
    });
    await fse.writeJson(path.join(teamaiHome, 'managed-mcp.json'), {
      claude: [{ name: 'team-mcp', hash: 'abc' }],
    });

    const teamConfig = makeTeamConfig({
      toolPaths: {
        claude: {
          skills: '.claude/skills',
          rules: '.claude/rules',
          settings: '.claude/settings.json',
          claudemd: '.claude/CLAUDE.md',
          mcp: '.claude.json',
          mcpProject: '.mcp.json',
        },
      },
      sharing: {
        skills: {},
        rules: { enforced: [] },
        docs: { localDir: `${teamaiHome}/docs` },
        env: { injectShellProfile: true },
      },
    });
    mockAutoDetectInit.mockResolvedValue({
      localConfig: makeLocalConfig(homeDir, repoPath),
      teamConfig,
    });

    await uninstall({ force: true });

    const after = await fse.readJson(path.join(homeDir, '.claude.json'));
    expect(after.mcpServers['team-mcp']).toBeUndefined();
    expect(after.mcpServers['my-own']).toEqual({ command: 'my-server' });
  });

  it('移除 OpenClaw 系 agent 的 HOOK.md 目录（无 settings 路径）', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    // Simulate an installed OpenClaw-family agent with teamai HOOK.md injected.
    const ocHookDir = path.join(homeDir, '.openclaw', 'hooks', 'teamai-status-report');
    await fse.ensureDir(ocHookDir);
    await fse.writeFile(path.join(ocHookDir, 'HOOK.md'), '---\nname: [teamai] status-report\n---\n');
    await fse.writeFile(path.join(ocHookDir, 'handler.ts'), '// teamai');

    const teamConfig = makeTeamConfig({
      toolPaths: {
        claude: { skills: '.claude/skills', rules: '.claude/rules', settings: '.claude/settings.json', claudemd: '.claude/CLAUDE.md' },
        openclaw: { skills: '.openclaw/skills', rules: '.openclaw/rules' }, // no settings → OpenClaw HOOK.md path
      },
      sharing: {
        skills: {},
        rules: { enforced: [] },
        docs: { localDir: `${teamaiHome}/docs` },
        env: { injectShellProfile: true },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    // The OpenClaw HOOK.md dir must be removed (regression: previously leaked).
    expect(await fse.pathExists(ocHookDir)).toBe(false);
  });

  it('project scope 卸载同时清掉用户级和项目级的 OpenCode plugin', async () => {
    const projectRoot = path.join(tmpDir, 'oc-project');
    const homeDir = path.join(tmpDir, 'home');
    const repoPath = path.join(projectRoot, '.teamai', 'team-repo');
    await fse.ensureDir(repoPath);
    await fse.writeFile(path.join(projectRoot, '.teamai', 'config.yaml'), 'scope: project');

    // teamai writes the plugin into the user dir; the project dir may still hold
    // a copy from an earlier layout, plus an agent-hook plugin.
    const userPlugin = path.join(homeDir, '.config', 'opencode', 'plugin');
    const projectPlugin = path.join(projectRoot, '.opencode', 'plugin');
    await fse.ensureDir(userPlugin);
    await fse.ensureDir(projectPlugin);
    await fse.writeFile(path.join(userPlugin, 'teamai-hooks.ts'), '// [teamai] hooks plugin');
    await fse.writeFile(path.join(projectPlugin, 'teamai-hooks.ts'), '// [teamai] hooks plugin');
    await fse.writeFile(path.join(projectPlugin, 'teamai-agent-legacy.ts'), '// [teamai] agent hook');
    await fse.writeFile(path.join(projectPlugin, 'my-own-plugin.ts'), '// mine');

    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const teamConfig = makeTeamConfig({
      toolPaths: {
        opencode: { skills: '.opencode/skills', rules: '.opencode/rules' }, // no settings → plugin path
      },
    });
    const localConfig = makeLocalConfig(projectRoot, repoPath, { scope: 'project', projectRoot });
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    expect(await fse.pathExists(path.join(userPlugin, 'teamai-hooks.ts'))).toBe(false);
    expect(await fse.pathExists(path.join(projectPlugin, 'teamai-hooks.ts'))).toBe(false);
    // Agent-hook sweep must delete inside the plugin dir, not a cwd-relative path.
    expect(await fse.pathExists(path.join(projectPlugin, 'teamai-agent-legacy.ts'))).toBe(false);
    // A user's own plugin is untouched.
    expect(await fse.pathExists(path.join(projectPlugin, 'my-own-plugin.ts'))).toBe(true);
  });

  // A relocated Claude Code root (toolRoots) moves the HOME hook file, but the
  // legacy <projectRoot> copy was written by a CLI that knew nothing about it —
  // so the two targets must be looked for at different paths.
  it('removes hooks from a relocated home root and from the legacy project copy', async () => {
    const projectRoot = path.join(tmpDir, 'relocated-project');
    const homeDir = path.join(tmpDir, 'home');
    const repoPath = path.join(projectRoot, '.teamai', 'team-repo');
    await fse.ensureDir(repoPath);

    const teamaiHooks = {
      hooks: {
        SessionStart: [{
          matcher: '*',
          hooks: [{ type: 'command', command: 'teamai hook-dispatch session-start' }],
          description: '[teamai] Auto-pull',
        }],
      },
    };
    const homeSettings = path.join(homeDir, '.claude-work', 'settings.json');
    const legacySettings = path.join(projectRoot, '.claude', 'settings.json');
    await fse.outputJson(homeSettings, teamaiHooks);
    await fse.outputJson(legacySettings, teamaiHooks);

    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(projectRoot, repoPath, {
      scope: 'project',
      projectRoot,
      toolRoots: { claude: path.join(homeDir, '.claude-work') },
    });
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    const cleaned = mockReconcileHooks.mock.calls.map((call) => call[0]);
    expect(cleaned).toContain(homeSettings);
    expect(cleaned).toContain(legacySettings);
    // The un-relocated home path is not a target and must not be created.
    expect(await fse.pathExists(path.join(homeDir, '.claude'))).toBe(false);
  });

  it('保留用户自建的 skills', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    // User's own skill must survive
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'my-own-skill', 'SKILL.md'))).toBe(true);
  });

  it('保留 CLAUDE.md 中非 teamai 的内容', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    const claudeMd = await fse.readFile(path.join(homeDir, '.claude', 'CLAUDE.md'), 'utf-8');
    expect(claudeMd).toContain('# My custom instructions');
    expect(claudeMd).not.toContain(TEAMAI_RULES_START);
    expect(claudeMd).not.toContain(TEAMAI_CULTURE_START);
    expect(claudeMd).not.toContain(TEAMAI_CLAUDEMD_START);
    expect(claudeMd).not.toContain(TEAMAI_RECALL_RULES_START);
  });

  it('shell profile 环境变量块被清理', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    const zshrc = await fse.readFile(path.join(homeDir, '.zshrc'), 'utf-8');
    expect(zshrc).not.toContain(TEAMAI_ENV_START);
    expect(zshrc).not.toContain(TEAMAI_ENV_END);
    expect(zshrc).not.toContain('env.sh');
    expect(zshrc).toContain('export PATH');
  });

  it('dry-run 不做任何更改', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ dryRun: true, force: true });

    // Nothing should be changed
    expect(mockReconcileHooks).not.toHaveBeenCalled();
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'team-skill'))).toBe(true);
    expect(await fse.pathExists(teamaiHome)).toBe(true);

    const claudeMd = await fse.readFile(path.join(homeDir, '.claude', 'CLAUDE.md'), 'utf-8');
    expect(claudeMd).toContain(TEAMAI_RULES_START);
  });

  it('dry-run 和卸载覆盖自定义 agents 及 OpenClaw workspace skills，同时保留用户资源', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    await fse.ensureDir(path.join(repoPath, 'agents', 'frontend'));
    await fse.writeFile(
      path.join(repoPath, 'agents', 'beta-proof-agent.yaml'),
      'name: beta-proof-agent\ndescription: Team agent\ninstructions: Help the team\n',
    );
    // Role-scoped agent (agents/<namespace>/) deploys flattened like the rest.
    await fse.writeFile(
      path.join(repoPath, 'agents', 'frontend', 'scoped-agent.yaml'),
      'name: scoped-agent\ndescription: Frontend agent\ninstructions: Help frontend\n',
    );
    await fse.ensureDir(path.join(repoPath, 'skills', 'former-role-skill'));
    await fse.writeFile(
      path.join(repoPath, 'skills', 'former-role-skill', 'SKILL.md'),
      '# Former Role Skill',
    );

    const managedAgentPaths = [
      path.join(homeDir, '.claude', 'agents', 'beta-proof-agent.md'),
      path.join(homeDir, '.codex', 'agents', 'beta-proof-agent.toml'),
      path.join(homeDir, '.cursor', 'agents', 'beta-proof-agent.md'),
      path.join(homeDir, '.codebuddy', 'agents', 'beta-proof-agent.md'),
      path.join(homeDir, '.opencode', 'agents', 'beta-proof-agent.md'),
      path.join(homeDir, '.claude', 'agents', 'scoped-agent.md'),
      path.join(homeDir, '.codex', 'agents', 'scoped-agent.toml'),
    ];
    for (const agentPath of managedAgentPaths) {
      await fse.ensureDir(path.dirname(agentPath));
      await fse.writeFile(agentPath, '# Managed agent');
    }

    const userAgentPath = path.join(homeDir, '.claude', 'agents', 'my-own-agent.md');
    await fse.writeFile(userAgentPath, '# User agent');
    const nestedUserAgentPath = path.join(
      homeDir,
      '.claude',
      'agents',
      'user-group',
      'beta-proof-agent.md',
    );
    await fse.ensureDir(path.dirname(nestedUserAgentPath));
    await fse.writeFile(nestedUserAgentPath, '# User agent with a managed-looking basename');

    const openclawManagedSkill = path.join(
      homeDir,
      '.openclaw',
      'workspace',
      'skills',
      'former-role-skill',
    );
    const openclawUserSkill = path.join(
      homeDir,
      '.openclaw',
      'workspace',
      'skills',
      'my-own-skill',
    );
    await fse.ensureDir(openclawManagedSkill);
    await fse.writeFile(path.join(openclawManagedSkill, 'SKILL.md'), '# Managed skill');
    await fse.ensureDir(openclawUserSkill);
    await fse.writeFile(path.join(openclawUserSkill, 'SKILL.md'), '# User skill');

    const teamConfig = makeTeamConfig({
      toolPaths: {
        claude: { skills: '.claude/skills', agents: '.claude/agents' },
        codex: { skills: '.codex/skills', agents: '.codex/agents' },
        cursor: { skills: '.cursor/skills', agents: '.cursor/agents' },
        codebuddy: { skills: '.codebuddy/skills', agents: '.codebuddy/agents' },
        opencode: { skills: '.opencode/skills', agents: '.opencode/agents' },
        openclaw: { skills: '.openclaw/skills' },
      },
    });
    mockAutoDetectInit.mockResolvedValue({
      localConfig: makeLocalConfig(homeDir, repoPath),
      teamConfig,
    });

    const lines: string[] = [];
    const spy = vi.spyOn(console, 'log').mockImplementation((...args: unknown[]) => {
      lines.push(args.map(String).join(' '));
    });
    await uninstall({ dryRun: true, force: true });
    spy.mockRestore();

    const summary = lines.join('\n');
    for (const agentPath of managedAgentPaths) {
      expect(summary).toContain(agentPath);
      expect(await fse.pathExists(agentPath)).toBe(true);
    }
    expect(summary).toContain(openclawManagedSkill);
    expect(await fse.pathExists(openclawManagedSkill)).toBe(true);

    await uninstall({ force: true });

    for (const agentPath of managedAgentPaths) {
      expect(await fse.pathExists(agentPath)).toBe(false);
    }
    expect(await fse.pathExists(openclawManagedSkill)).toBe(false);
    expect(await fse.pathExists(userAgentPath)).toBe(true);
    expect(await fse.pathExists(nestedUserAgentPath)).toBe(true);
    expect(await fse.pathExists(openclawUserSkill)).toBe(true);
  });

  it('uninstall summary lists teamai-managed MCP servers', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    await fse.writeJson(path.join(teamaiHome, 'managed-mcp.json'), {
      claude: [{ name: 'gpu-analysis', hash: 'abc' }],
      cursor: [{ name: 'context7', hash: 'def' }],
    });

    mockAutoDetectInit.mockResolvedValue({
      localConfig: makeLocalConfig(homeDir, repoPath),
      teamConfig: makeTeamConfig({
        toolPaths: {
          claude: {
            skills: '.claude/skills',
            rules: '.claude/rules',
            settings: '.claude/settings.json',
            claudemd: '.claude/CLAUDE.md',
            mcp: '.claude.json',
          },
        },
      }),
    });

    const lines: string[] = [];
    const spy = vi.spyOn(console, 'log').mockImplementation((...args: unknown[]) => {
      lines.push(args.map(String).join(' '));
    });

    await uninstall({ dryRun: true, force: true });
    spy.mockRestore();

    const summary = lines.join('\n');
    expect(summary).toContain('MCP servers (2):');
    expect(summary).toContain('claude/gpu-analysis');
    expect(summary).toContain('cursor/context7');
  });

  it('什么都不存在时正常退出', async () => {
    const homeDir = path.join(tmpDir, 'empty-home');
    const repoPath = path.join(tmpDir, 'empty-repo');
    await fse.ensureDir(repoPath);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/bash');

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    // Should not throw
    await expect(uninstall({ force: true })).resolves.not.toThrow();
  });

  it('配置加载失败时仍然移除 ~/.teamai/', async () => {
    const homeDir = path.join(tmpDir, 'broken-home');
    const teamaiHome = path.join(homeDir, '.teamai');
    await fse.ensureDir(teamaiHome);
    await fse.writeFile(path.join(teamaiHome, 'config.yaml'), 'broken');
    vi.stubEnv('HOME', homeDir);

    mockAutoDetectInit.mockRejectedValue(new Error('Config not found'));

    await uninstall({ force: true });

    expect(await fse.pathExists(teamaiHome)).toBe(false);
  });

  it('keeps the ownership manifest when a full uninstall cannot restore an externally edited model', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');
    const mcpPath = path.join(homeDir, '.claude.json');
    await fse.writeJson(mcpPath, { mcpServers: { 'team-mcp': { type: 'http', url: 'https://team.example/mcp' } } });
    await fse.writeJson(path.join(teamaiHome, 'managed-mcp.json'), { claude: [{ name: 'team-mcp', hash: 'abc' }] });
    mockAutoDetectInit.mockResolvedValue({
      localConfig: makeLocalConfig(homeDir, repoPath),
      teamConfig: makeTeamConfig({ toolPaths: { claude: {
        skills: '.claude/skills', rules: '.claude/rules', settings: '.claude/settings.json',
        claudemd: '.claude/CLAUDE.md', mcp: '.claude.json', mcpProject: '.mcp.json',
      } } }),
    });
    const profile = resolveProfile({ source: 'local', profile: ModelProfileSchema.parse({
      id: 'gateway', name: 'Gateway', base_url: 'https://gateway.example.test', api_key: '${API_KEY}',
      model_groups: [{ protocols: ['anthropic'], models: ['team-model'] }],
    }) }, { 'local:gateway': { API_KEY: { value: 'test-key' } } });
    expect((await switchModelProfile(profile, ['claude']))[0].status).toBe('switched');
    const settingsPath = path.join(homeDir, '.claude', 'settings.json');
    const settings = await fse.readJson(settingsPath);
    settings.env.ANTHROPIC_AUTH_TOKEN = 'externally-edited';
    await fse.writeJson(settingsPath, settings);

    await uninstall({ force: true });
    expect(await fse.pathExists(path.join(teamaiHome, 'models', 'managed.json'))).toBe(true);
    expect((await fse.readJson(settingsPath)).env.ANTHROPIC_AUTH_TOKEN).toBe('externally-edited');
    expect((await fse.readJson(mcpPath)).mcpServers).toHaveProperty('team-mcp');
    expect(process.exitCode).toBe(1);
    process.exitCode = 0;
  });

  it('project scope 定位正确目录', async () => {
    const projectRoot = path.join(tmpDir, 'my-project');
    const repoPath = path.join(projectRoot, '.teamai', 'team-repo');
    const teamaiHome = path.join(projectRoot, '.teamai');

    // Team repo
    await fse.ensureDir(path.join(repoPath, 'skills', 'proj-skill'));
    await fse.writeFile(path.join(repoPath, 'skills', 'proj-skill', 'SKILL.md'), '# Proj Skill');

    // Tool dirs at project root
    await fse.ensureDir(path.join(projectRoot, '.claude', 'skills', 'proj-skill'));
    await fse.writeFile(path.join(projectRoot, '.claude', 'skills', 'proj-skill', 'SKILL.md'), '# Proj Skill');

    // .teamai/ at project root
    await fse.writeFile(path.join(teamaiHome, 'config.yaml'), 'scope: project');

    vi.stubEnv('HOME', path.join(tmpDir, 'home'));
    vi.stubEnv('SHELL', '/bin/bash');

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(projectRoot, repoPath, {
      scope: 'project',
      projectRoot,
    });
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    const globalSettings = path.join(process.env.HOME!, '.claude', 'settings.json');
    await fse.outputJson(globalSettings, { env: { KEEP_ME: 'yes' } });
    const profile = resolveProfile({ source: 'local', profile: ModelProfileSchema.parse({
      id: 'gateway', name: 'Gateway', base_url: 'https://gateway.example.test', api_key: '${API_KEY}',
      model_groups: [{ protocols: ['anthropic'], models: ['team-model'] }],
    }) }, { 'local:gateway': { API_KEY: { value: 'test-key' } } });
    expect((await switchModelProfile(profile, ['claude']))[0].status).toBe('switched');
    const active = await fse.readJson(globalSettings);

    await uninstall({ force: true });

    // Project-scope skill removed
    expect(await fse.pathExists(path.join(projectRoot, '.claude', 'skills', 'proj-skill'))).toBe(false);
    // Project .teamai/ removed
    expect(await fse.pathExists(teamaiHome)).toBe(false);
    expect(await fse.readJson(globalSettings)).toEqual(active);
    expect(await fse.pathExists(path.join(process.env.HOME!, '.teamai', 'models', 'managed.json'))).toBe(true);
  });

  it('non-self project scope removes hooks from HOME, where #370 injects them (not <projectRoot>)', async () => {
    const projectRoot = path.join(tmpDir, 'proj-hooks');
    const repoPath = path.join(projectRoot, '.teamai', 'team-repo');
    const homeDir = path.join(tmpDir, 'home');
    await fse.ensureDir(repoPath);
    await fse.ensureDir(path.join(projectRoot, '.teamai'));
    await fse.writeFile(path.join(projectRoot, '.teamai', 'config.yaml'), 'scope: project');

    // #370: a non-self project scope injects its hooks into HOME, not projectRoot.
    await fse.ensureDir(path.join(homeDir, '.claude'));
    await fse.writeJson(path.join(homeDir, '.claude', 'settings.json'), {
      hooks: { SessionStart: [{ matcher: '*', hooks: [{ type: 'command', command: 'teamai hook-dispatch session-start' }], description: '[teamai] Auto-pull' }] },
    });

    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/bash');

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(projectRoot, repoPath, { scope: 'project', projectRoot });
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    // The reported bug (#1): uninstall scanned <projectRoot> and left the HOME
    // SessionStart hook live forever. It must target the HOME settings file.
    expect(mockReconcileHooks).toHaveBeenCalledWith(
      path.join(homeDir, '.claude', 'settings.json'),
      'claude',
      [],
      expect.objectContaining({ removeAll: true, manifestPath: expect.stringContaining('managed-hooks.json') }),
    );
    // …and never a <projectRoot> settings copy (there is none in this fixture).
    const targetedProjectRoot = mockReconcileHooks.mock.calls.some(
      (c) => String(c[0]).startsWith(path.join(projectRoot, '.claude')),
    );
    expect(targetedProjectRoot).toBe(false);
  });

  // #667: hook discovery must resolve the settings *file* at the scope hooks
  // were injected into, not at the config's scope. Qoder CN reads
  // `~/.qoder-cn/` for its user scope, so a non-self project scope (which
  // injects into HOME, #370) has to look for `~/.qoder-cn/settings.json`; the
  // project-scope name resolved to the *other* build's `~/.qoder/settings.json`
  // and left the CN hooks in HOME forever.
  it('non-self project scope discovers Qoder CN hooks in ~/.qoder-cn, not ~/.qoder', async () => {
    const projectRoot = path.join(tmpDir, 'proj-qcn');
    const repoPath = path.join(projectRoot, '.teamai', 'team-repo');
    const homeDir = path.join(tmpDir, 'home');
    await fse.ensureDir(repoPath);
    await fse.ensureDir(path.join(projectRoot, '.teamai'));
    await fse.writeFile(path.join(projectRoot, '.teamai', 'config.yaml'), 'scope: project');

    await fse.ensureDir(path.join(homeDir, '.qoder-cn'));
    await fse.writeJson(path.join(homeDir, '.qoder-cn', 'settings.json'), {
      hooks: {
        SessionStart: [{
          matcher: '*',
          hooks: [{ type: 'command', command: 'teamai hook-dispatch session-start --tool qoder-cn' }],
          description: '[teamai] Hook dispatch session-start',
        }],
      },
    });

    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/bash');

    // The shipped table, not a fixture: `qoder-cn`'s project scope is Qoder's
    // `<root>/.qoder/`, which is exactly what made the lookup wrong.
    const teamConfig = TeamaiConfigSchema.parse({ team: 'test', repo: 'test/repo' });
    const localConfig = makeLocalConfig(projectRoot, repoPath, { scope: 'project', projectRoot });
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    expect(mockReconcileHooks).toHaveBeenCalledWith(
      path.join(homeDir, '.qoder-cn', 'settings.json'),
      'qoder-cn',
      [],
      expect.objectContaining({ removeAll: true, manifestPath: expect.stringContaining('managed-hooks.json') }),
    );
    const targetedIntlFile = mockReconcileHooks.mock.calls.some(
      (c) => String(c[0]) === path.join(homeDir, '.qoder', 'settings.json'),
    );
    expect(targetedIntlFile).toBe(false);
  });

  it('命名空间 skills 正确处理', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    // Add a namespaced skill in team repo (namespace dir has no SKILL.md)
    await fse.ensureDir(path.join(repoPath, 'skills', 'backend'));
    await fse.ensureDir(path.join(repoPath, 'skills', 'backend', 'ns-skill'));
    await fse.writeFile(path.join(repoPath, 'skills', 'backend', 'ns-skill', 'SKILL.md'), '# NS Skill');

    // Synced to tool dir
    await fse.ensureDir(path.join(homeDir, '.claude', 'skills', 'ns-skill'));
    await fse.writeFile(path.join(homeDir, '.claude', 'skills', 'ns-skill', 'SKILL.md'), '# NS Skill');

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    // Both flat and namespaced team skills removed
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'team-skill'))).toBe(false);
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'ns-skill'))).toBe(false);
    // User skill preserved
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'my-own-skill'))).toBe(true);
  });

  it('移除 CLI built-in 资源（recall agent/rule + built-in skills）', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const codexRecallAgent = path.join(homeDir, '.codex', 'agents', 'teamai-recall.toml');
    await fse.ensureDir(path.dirname(codexRecallAgent));
    await fse.writeFile(codexRecallAgent, 'developer_instructions = "Recall"\n');

    const teamConfig = makeTeamConfig({
      toolPaths: {
        claude: {
          skills: '.claude/skills',
          rules: '.claude/rules',
          settings: '.claude/settings.json',
          claudemd: '.claude/CLAUDE.md',
          agents: '.claude/agents',
        },
        codex: { agents: '.codex/agents' },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    // Built-in recall agent + rule removed
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'agents', 'teamai-recall.md'))).toBe(false);
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'rules', 'teamai-recall.md'))).toBe(false);
    expect(await fse.pathExists(codexRecallAgent)).toBe(false);
    // Built-in skills removed: the deployed stub, and the directories earlier
    // releases left behind.
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'teamai'))).toBe(false);
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'teamai-share-learnings'))).toBe(false);
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'team-wiki-codebase'))).toBe(false);
    // User's own skill still preserved
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'my-own-skill'))).toBe(true);
  });

  it('removes only the packaged files from a CLI-owned skill dir, keeping what the member added', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    // A machine that upgraded through the pre-stub releases: the packaged trees,
    // with the member's own files mixed into them. Deployment never wrote those
    // files and never deleted them, so uninstall must not either.
    const skills = path.join(homeDir, '.claude', 'skills');
    const stub = path.join(skills, 'teamai');
    await fse.outputFile(path.join(stub, 'SKILL.md'), shipped('teamai', 'SKILL.md'));
    await fse.outputFile(path.join(stub, 'references', 'setup-admin.md'), shipped('teamai', 'references/setup-admin.md'));
    await fse.outputFile(path.join(stub, 'references', 'team-playbook.md'), '# mine\n');

    const legacy = path.join(skills, 'team-wiki-codebase');
    await fse.outputFile(path.join(legacy, 'SKILL.md'), shipped('team-wiki-codebase', 'SKILL.md'));
    await fse.outputFile(path.join(legacy, 'scripts', 'scan_repo.py'), shipped('team-wiki-codebase', 'scripts/scan_repo.py'));
    await fse.outputFile(path.join(legacy, 'references', 'methodology', 'my-notes.md'), '# mine\n');

    // Nothing of the member's in this one, so it goes whole.
    const legacyShare = path.join(skills, 'teamai-share-learnings');
    await fse.outputFile(path.join(legacyShare, 'SKILL.md'), shipped('teamai-share-learnings', 'SKILL.md'));

    const teamConfig = makeTeamConfig({
      toolPaths: {
        claude: {
          skills: '.claude/skills',
          rules: '.claude/rules',
          settings: '.claude/settings.json',
          claudemd: '.claude/CLAUDE.md',
          agents: '.claude/agents',
        },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    // The member's files, and the directories holding them, survive.
    expect(await fse.pathExists(path.join(stub, 'references', 'team-playbook.md'))).toBe(true);
    expect(await fse.pathExists(path.join(legacy, 'references', 'methodology', 'my-notes.md'))).toBe(true);
    // Everything TeamAI packaged is gone.
    expect(await fse.pathExists(path.join(stub, 'SKILL.md'))).toBe(false);
    expect(await fse.pathExists(path.join(stub, 'references', 'setup-admin.md'))).toBe(false);
    expect(await fse.pathExists(path.join(legacy, 'SKILL.md'))).toBe(false);
    expect(await fse.pathExists(path.join(legacy, 'scripts'))).toBe(false);
    // A directory with nothing of the member's in it still goes whole.
    expect(await fse.pathExists(legacyShare)).toBe(false);
  });

  it('names the file and the error when a packaged file cannot be deleted, instead of calling the directory kept', async () => {
    if (process.getuid?.() === 0) return; // root ignores directory permissions
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');
    const stubDir = path.join(homeDir, '.claude', 'skills', 'teamai');
    await fse.chmod(stubDir, 0o555);

    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig: makeTeamConfig() });
    const { log } = await import('../utils/logger.js');
    try {
      await uninstall({ force: true });
    } finally {
      await fse.chmod(stubDir, 0o755);
    }

    const warnings = (log.warn as ReturnType<typeof vi.fn>).mock.calls.map((c) => String(c[0]));
    const about = warnings.filter((w) => w.includes(stubDir));
    expect(about).toHaveLength(1);
    expect(about[0]).toContain('Could not delete packaged files under');
    expect(about[0]).toContain(path.join(stubDir, 'SKILL.md'));
    expect(about[0]).not.toContain('did not put there');
    expect(await fse.pathExists(path.join(stubDir, 'SKILL.md'))).toBe(true);
  });

  it('removes the stub the installed CLI deployed, byte for byte, and keeps a same-named skill of the member\'s', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');
    const skills = path.join(homeDir, '.claude', 'skills');
    // What `teamai pull` writes now: the packaged stub, verbatim.
    await fse.copy(path.join(PACKAGE_ROOT, 'skills', 'teamai', 'SKILL.md'), path.join(skills, 'teamai', 'SKILL.md'));
    // A skill the member wrote under a legacy name: no content a release shipped.
    await fse.outputFile(path.join(skills, 'team-wiki-codebase', 'SKILL.md'), '---\nname: team-wiki-codebase\n---\n# mine\n');

    mockAutoDetectInit.mockResolvedValue({ localConfig: makeLocalConfig(homeDir, repoPath), teamConfig: makeTeamConfig() });
    await uninstall({ force: true });

    expect(await fse.pathExists(path.join(skills, 'teamai'))).toBe(false);
    expect(await fse.readFile(path.join(skills, 'team-wiki-codebase', 'SKILL.md'), 'utf8')).toContain('# mine');
  });

  it('does not delete through a linked skills root, the same line pull stops at', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');
    // The member's dotfiles checkout, linked in as ~/.claude/skills.
    const dotfiles = path.join(tmpDir, 'dotfiles-skills');
    await fse.move(path.join(homeDir, '.claude', 'skills'), dotfiles);
    await fse.symlink(dotfiles, path.join(homeDir, '.claude', 'skills'), 'dir');

    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig: makeTeamConfig() });
    await uninstall({ force: true });

    expect(await fse.pathExists(path.join(dotfiles, 'teamai', 'SKILL.md'))).toBe(true);
  });

  it('does not delete through a linked agent directory either, a link higher up the path', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');
    const dotfiles = path.join(tmpDir, 'dotfiles-claude');
    await fse.move(path.join(homeDir, '.claude'), dotfiles);
    await fse.symlink(dotfiles, path.join(homeDir, '.claude'), 'dir');

    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig: makeTeamConfig() });
    await uninstall({ force: true });

    expect(await fse.pathExists(path.join(dotfiles, 'skills', 'teamai', 'SKILL.md'))).toBe(true);
  });

  it('does not delete through a linked COPILOT_HOME, Copilot\'s own base directory in user scope', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');
    const target = path.join(tmpDir, 'dotfiles-copilot');
    await fse.ensureDir(path.join(target, 'skills', 'teamai'));
    await fse.writeFile(path.join(target, 'skills', 'teamai', 'SKILL.md'), shipped('teamai', 'SKILL.md'));
    await fse.symlink(target, path.join(homeDir, '.copilot'), 'dir');

    const localConfig = makeLocalConfig(homeDir, repoPath);
    const teamConfig = makeTeamConfig();
    teamConfig.toolPaths.copilot = { skills: '.github/skills', userScope: { skills: 'skills' } };
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });
    await uninstall({ force: true });

    expect(await fse.pathExists(path.join(target, 'skills', 'teamai', 'SKILL.md'))).toBe(true);
  });

  it('removes the stub where Hermes keeps skills, under HERMES_HOME outside the home directory', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');
    const hermesHome = path.join(tmpDir, 'elsewhere', 'hermes');
    vi.stubEnv('HERMES_HOME', hermesHome);
    const stub = path.join(hermesHome, 'skills', 'teamai', 'SKILL.md');
    await fse.ensureDir(path.dirname(stub));
    await fse.writeFile(stub, shipped('teamai', 'SKILL.md'));

    const localConfig = makeLocalConfig(homeDir, repoPath);
    const teamConfig = makeTeamConfig();
    teamConfig.toolPaths.hermes = { skills: '.hermes/skills' };
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });
    await uninstall({ force: true });

    expect(await fse.pathExists(stub)).toBe(false);
  });

  it('removes the stub Codex kept in the shared .agents/skills root, and nothing else there', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    // resolveSkillDestination writes Codex's copy here whenever the skill
    // already lives in the shared root, so this is where the stub ends up on a
    // machine that has ever had one.
    const sharedStub = path.join(homeDir, '.agents', 'skills', 'teamai');
    await fse.ensureDir(sharedStub);
    await fse.writeFile(path.join(sharedStub, 'SKILL.md'), shipped('teamai', 'SKILL.md'));
    const sharedUserSkill = path.join(homeDir, '.agents', 'skills', 'my-own-skill');
    await fse.ensureDir(sharedUserSkill);
    await fse.writeFile(path.join(sharedUserSkill, 'SKILL.md'), '# Mine\n');

    const teamConfig = makeTeamConfig({
      toolPaths: {
        claude: {
          skills: '.claude/skills',
          rules: '.claude/rules',
          settings: '.claude/settings.json',
          claudemd: '.claude/CLAUDE.md',
          agents: '.claude/agents',
        },
        codex: { skills: '.codex/skills' },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    expect(await fse.pathExists(sharedStub)).toBe(false);
    expect(await fse.pathExists(sharedUserSkill)).toBe(true);
  });

  it('清理 CLAUDE.md 中所有 teamai section（culture/claudemd/recall-rules）', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    const claudeMd = await fse.readFile(path.join(homeDir, '.claude', 'CLAUDE.md'), 'utf-8');
    expect(claudeMd).toContain('# My custom instructions');
    expect(claudeMd).not.toContain(TEAMAI_RULES_START);
    expect(claudeMd).not.toContain(TEAMAI_RULES_END);
    expect(claudeMd).not.toContain(TEAMAI_CULTURE_START);
    expect(claudeMd).not.toContain(TEAMAI_CULTURE_END);
    expect(claudeMd).not.toContain(TEAMAI_CLAUDEMD_START);
    expect(claudeMd).not.toContain(TEAMAI_CLAUDEMD_END);
    expect(claudeMd).not.toContain(TEAMAI_RECALL_RULES_START);
    expect(claudeMd).not.toContain(TEAMAI_RECALL_RULES_END);
    expect(claudeMd).not.toContain('Team Culture');
    expect(claudeMd).not.toContain('Shared Instructions');
    expect(claudeMd).not.toContain('Recall Rules');
  });

  it('removes TeamAI blocks from COPILOT_HOME instructions and preserves user text', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    const copilotHome = path.join(tmpDir, 'copilot-home');
    const instructionsPath = path.join(copilotHome, 'copilot-instructions.md');
    const userInstructions = '# Personal Copilot instructions';
    await fse.ensureDir(copilotHome);
    await fse.writeFile(instructionsPath, [
      userInstructions,
      '',
      TEAMAI_CULTURE_START,
      'Team culture',
      TEAMAI_CULTURE_END,
      '',
      TEAMAI_CLAUDEMD_START,
      'Shared instructions',
      TEAMAI_CLAUDEMD_END,
      '',
    ].join('\n'));
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('COPILOT_HOME', copilotHome);
    vi.stubEnv('SHELL', '/bin/zsh');

    const teamConfig = TeamaiConfigSchema.parse({
      team: 'test',
      repo: 'https://github.com/example/team.git',
    });
    const localConfig = makeLocalConfig(homeDir, repoPath, { enabledAgents: ['copilot'] });
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'copilot' });

    const result = await fse.readFile(instructionsPath, 'utf8');
    expect(result).toContain(userInstructions);
    expect(result).not.toContain(TEAMAI_CULTURE_START);
    expect(result).not.toContain(TEAMAI_CULTURE_END);
    expect(result).not.toContain(TEAMAI_CLAUDEMD_START);
    expect(result).not.toContain(TEAMAI_CLAUDEMD_END);
  });

  it('多工具场景：清理 codebuddy 和 claude-internal 的 CLAUDE.md', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    // Setup codebuddy CODEBUDDY.md with teamai sections
    const codebuddyMd = [
      '# CodeBuddy Config',
      '',
      TEAMAI_RULES_START,
      '## Team Rules',
      TEAMAI_RULES_END,
      '',
      TEAMAI_RECALL_RULES_START,
      '## Recall Rules',
      'Use recall subagent.',
      TEAMAI_RECALL_RULES_END,
      '',
    ].join('\n');
    await fse.ensureDir(path.join(homeDir, '.codebuddy'));
    await fse.writeFile(path.join(homeDir, '.codebuddy', 'CODEBUDDY.md'), codebuddyMd);

    // Setup claude-internal CLAUDE.md with teamai sections
    const claudeInternalMd = [
      '# Internal Config',
      '',
      TEAMAI_CULTURE_START,
      '## Culture',
      'Be excellent.',
      TEAMAI_CULTURE_END,
      '',
      TEAMAI_CLAUDEMD_START,
      '## Shared',
      'Use TypeScript.',
      TEAMAI_CLAUDEMD_END,
      '',
    ].join('\n');
    await fse.ensureDir(path.join(homeDir, '.claude-internal'));
    await fse.writeFile(path.join(homeDir, '.claude-internal', 'CLAUDE.md'), claudeInternalMd);

    const teamConfig = makeTeamConfig({
      toolPaths: {
        claude: {
          skills: '.claude/skills',
          rules: '.claude/rules',
          settings: '.claude/settings.json',
          claudemd: '.claude/CLAUDE.md',
        },
        codebuddy: {
          skills: '.codebuddy/skills',
          rules: '.codebuddy/rules',
          settings: '.codebuddy/settings.json',
          claudemd: '.codebuddy/CODEBUDDY.md',
        },
        'claude-internal': {
          skills: '.claude-internal/skills',
          rules: '.claude-internal/rules',
          settings: '.claude-internal/settings.json',
          claudemd: '.claude-internal/CLAUDE.md',
        },
      },
      sharing: {
        skills: {},
        rules: { enforced: [] },
        docs: { localDir: `${path.join(homeDir, '.teamai')}/docs` },
        env: { injectShellProfile: true },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    // codebuddy: user content preserved, teamai sections removed
    const codebuddyResult = await fse.readFile(path.join(homeDir, '.codebuddy', 'CODEBUDDY.md'), 'utf-8');
    expect(codebuddyResult).toContain('# CodeBuddy Config');
    expect(codebuddyResult).not.toContain(TEAMAI_RULES_START);
    expect(codebuddyResult).not.toContain(TEAMAI_RECALL_RULES_START);

    // claude-internal: user content preserved, teamai sections removed
    const internalResult = await fse.readFile(path.join(homeDir, '.claude-internal', 'CLAUDE.md'), 'utf-8');
    expect(internalResult).toContain('# Internal Config');
    expect(internalResult).not.toContain(TEAMAI_CULTURE_START);
    expect(internalResult).not.toContain(TEAMAI_CLAUDEMD_START);
  });

  it('--agent claude 且只有 claude 一个工具 → 全删含共享', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'claude' });

    // claude team-skill removed
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'team-skill'))).toBe(false);
    // ~/.teamai removed (claude was the last tool)
    expect(await fse.pathExists(teamaiHome)).toBe(false);
    // reconcileHooks called with claude + removeAll
    expect(mockReconcileHooks).toHaveBeenCalledWith(
      path.join(homeDir, '.claude', 'settings.json'),
      'claude',
      [],
      expect.objectContaining({ removeAll: true }),
    );
  });

  it('--agent copilot honors COPILOT_HOME and removes only TeamAI-owned resources', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    const copilotHome = path.join(tmpDir, 'custom-copilot-home');
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('COPILOT_HOME', copilotHome);
    vi.stubEnv('SHELL', '/bin/zsh');

    await fse.ensureDir(path.join(copilotHome, 'skills', 'team-skill'));
    await fse.writeFile(path.join(copilotHome, 'skills', 'team-skill', 'SKILL.md'), '# Team Skill');
    await fse.ensureDir(path.join(copilotHome, 'skills', 'personal-skill'));
    await fse.writeFile(path.join(copilotHome, 'skills', 'personal-skill', 'SKILL.md'), '# Personal');
    await fse.ensureDir(path.join(copilotHome, 'instructions'));
    await fse.writeFile(path.join(copilotHome, 'instructions', 'team-rule.instructions.md'), '# Team Rule');
    await fse.writeFile(path.join(copilotHome, 'instructions', 'personal.instructions.md'), '# Personal');
    const hookPath = path.join(copilotHome, 'hooks', 'teamai.json');
    await fse.ensureDir(path.dirname(hookPath));
    await fse.writeJson(hookPath, {
      version: 1,
      hooks: {
        SessionStart: [{
          type: 'command',
          bash: 'teamai hook-dispatch session-start --tool copilot',
          powershell: 'teamai hook-dispatch session-start --tool copilot',
          command: 'teamai hook-dispatch session-start --tool copilot',
        }],
      },
    });

    const teamConfig = makeTeamConfig({
      toolPaths: {
        copilot: {
          skills: '.github/skills',
          rules: '.github/instructions',
          hooks: '.github/hooks/teamai.json',
          userScope: { skills: 'skills', rules: 'instructions', hooks: 'hooks/teamai.json' },
        },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath, { enabledAgents: ['copilot'] });
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'copilot' });

    expect(await fse.pathExists(path.join(copilotHome, 'skills', 'team-skill'))).toBe(false);
    expect(await fse.pathExists(path.join(copilotHome, 'instructions', 'team-rule.instructions.md'))).toBe(false);
    expect(await fse.pathExists(path.join(copilotHome, 'skills', 'personal-skill'))).toBe(true);
    expect(await fse.pathExists(path.join(copilotHome, 'instructions', 'personal.instructions.md'))).toBe(true);
    expect(mockReconcileHooks).toHaveBeenCalledWith(
      hookPath,
      'copilot',
      [],
      expect.objectContaining({ removeAll: true }),
    );
  });

  it('--agent claude 但 codex 仍有资源 → 保留共享', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    // Set up codex with a team-skill so discoverToolResources finds resources
    await fse.ensureDir(path.join(homeDir, '.codex', 'skills', 'team-skill'));
    await fse.writeFile(path.join(homeDir, '.codex', 'skills', 'team-skill', 'SKILL.md'), '# Team Skill');

    const teamConfig = makeTeamConfig({
      toolPaths: {
        claude: {
          skills: '.claude/skills',
          rules: '.claude/rules',
          settings: '.claude/settings.json',
          claudemd: '.claude/CLAUDE.md',
          agents: '.claude/agents',
        },
        codex: {
          skills: '.codex/skills',
          rules: '.codex/rules',
        },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'claude' });

    // claude team-skill removed
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'team-skill'))).toBe(false);
    // ~/.teamai NOT removed (codex still has resources)
    expect(await fse.pathExists(teamaiHome)).toBe(true);
    // codex team-skill still exists
    expect(await fse.pathExists(path.join(homeDir, '.codex', 'skills', 'team-skill'))).toBe(true);
    // Exclusion persisted so the next pull won't resurrect claude: added to
    // disabledAgents (user scope → saveLocalConfig).
    expect(mockSaveLocalConfig).toHaveBeenCalledTimes(1);
    const savedCfg = mockSaveLocalConfig.mock.calls[0][0] as LocalConfig;
    expect(savedCfg.disabledAgents).toContain('claude');
    // No prior whitelist existed → enabledAgents must stay undefined, NOT collapse
    // to [] (which the hook path reads as "whitelist nothing" and would wrongly
    // stop hook sync for the remaining tools too).
    expect(savedCfg.enabledAgents).toBeUndefined();
  });

  it('--agent 卸载在已有 enabledAgents 白名单时只移除目标工具', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    await fse.ensureDir(path.join(homeDir, '.codex', 'skills', 'team-skill'));
    await fse.writeFile(path.join(homeDir, '.codex', 'skills', 'team-skill', 'SKILL.md'), '# Team Skill');

    const teamConfig = makeTeamConfig({
      toolPaths: {
        claude: {
          skills: '.claude/skills',
          rules: '.claude/rules',
          settings: '.claude/settings.json',
          claudemd: '.claude/CLAUDE.md',
          agents: '.claude/agents',
        },
        codex: { skills: '.codex/skills', rules: '.codex/rules' },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath);
    localConfig.enabledAgents = ['claude', 'codex'];
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'claude' });

    expect(mockSaveLocalConfig).toHaveBeenCalledTimes(1);
    const savedCfg = mockSaveLocalConfig.mock.calls[0][0] as LocalConfig;
    // Existing whitelist is pruned of the target only; codex stays enabled.
    expect(savedCfg.enabledAgents).toEqual(['codex']);
    expect(savedCfg.disabledAgents).toContain('claude');
  });

  it('allows an explicit DSH binding to be removed before the first pull', async () => {
    const homeDir = path.join(tmpDir, 'empty-special-home');
    const repoPath = path.join(tmpDir, 'empty-special-repo');
    const dshRoot = path.join(tmpDir, 'custom dsh root');
    await Promise.all([
      fse.ensureDir(path.join(homeDir, '.teamai')),
      fse.ensureDir(repoPath),
      fse.ensureDir(dshRoot),
    ]);
    vi.stubEnv('HOME', homeDir);
    const teamConfig = makeTeamConfig({
      toolPaths: { dsh: { probe: '.dsh', skills: '.dsh/skills', instruction: '.dsh/AGENTS.md' } },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath, {
      enabledAgents: ['deepseek-harness'],
      hostRoots: { dsh: dshRoot },
    });
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'deepseek-harness' });

    expect(mockSaveLocalConfig).toHaveBeenCalledTimes(1);
    const savedCfg = mockSaveLocalConfig.mock.calls[0][0] as LocalConfig;
    expect(savedCfg.enabledAgents).toEqual([]);
    expect(savedCfg.disabledAgents).toContain('dsh');
    expect(savedCfg.hostRoots).toBeUndefined();
    expect(await fse.pathExists(dshRoot)).toBe(true);
  });

  it('--agent unknown → 报错不删', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    const prevExitCode = process.exitCode;
    process.exitCode = undefined;
    await uninstall({ force: true, agent: 'nonexistent' });

    // claude team-skill still exists
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'team-skill'))).toBe(true);
    // ~/.teamai still exists
    expect(await fse.pathExists(teamaiHome)).toBe(true);
    // reconcileHooks not called
    expect(mockReconcileHooks).not.toHaveBeenCalled();
    // Unknown tool sets a non-zero exit code (so scripts/CI see the failure)
    expect(process.exitCode).toBe(2);
    process.exitCode = prevExitCode;
  });

  it('--agent 卸载最后一个工具时移除共享资源（已剥离 hooks 的工具不算占用）', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    // claude settings.json has only a non-teamai user hook (simulates hooks already stripped)
    await fse.writeJson(path.join(homeDir, '.claude', 'settings.json'), {
      hooks: { SessionStart: [{ matcher: '*', hooks: [{ type: 'command', command: 'echo hi' }] }] },
    });
    // Remove all teamai resources from claude so it has zero teamai presence
    await fse.remove(path.join(homeDir, '.claude', 'skills', 'team-skill'));
    await fse.remove(path.join(homeDir, '.claude', 'skills', 'teamai'));
    await fse.remove(path.join(homeDir, '.claude', 'skills', 'teamai-share-learnings'));
    await fse.remove(path.join(homeDir, '.claude', 'skills', 'team-wiki-codebase'));
    await fse.remove(path.join(homeDir, '.claude', 'rules', 'team-rule.md'));
    await fse.remove(path.join(homeDir, '.claude', 'rules', 'teamai-recall.md'));
    await fse.remove(path.join(homeDir, '.claude', 'agents', 'teamai-recall.md'));
    await fse.remove(path.join(homeDir, '.claude', 'CLAUDE.md'));

    // codex has one team-skill
    await fse.ensureDir(path.join(homeDir, '.codex', 'skills', 'team-skill'));
    await fse.writeFile(path.join(homeDir, '.codex', 'skills', 'team-skill', 'SKILL.md'), '# Team Skill');

    const teamConfig = makeTeamConfig({
      toolPaths: {
        claude: {
          skills: '.claude/skills',
          rules: '.claude/rules',
          settings: '.claude/settings.json',
          claudemd: '.claude/CLAUDE.md',
          agents: '.claude/agents',
        },
        codex: {
          skills: '.codex/skills',
          rules: '.codex/rules',
        },
      },
    });
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'codex' });

    // codex team-skill removed
    expect(await fse.pathExists(path.join(homeDir, '.codex', 'skills', 'team-skill'))).toBe(false);
    // ~/.teamai removed — claude's settings.json has no teamai hooks, so it doesn't block shared removal
    expect(await fse.pathExists(teamaiHome)).toBe(false);
    // Last-tool uninstall deletes ~/.teamai, so there is no config to persist to.
    expect(mockSaveLocalConfig).not.toHaveBeenCalled();
    expect(mockSaveLocalConfigForScope).not.toHaveBeenCalled();
  });

  it('未检测到配置 + --agent → 返回不删', async () => {
    const homeDir = path.join(tmpDir, 'no-config-home');
    const teamaiHome = path.join(homeDir, '.teamai');
    await fse.ensureDir(teamaiHome);
    vi.stubEnv('HOME', homeDir);

    mockAutoDetectInit.mockRejectedValue(new Error('no config'));

    await uninstall({ force: true, agent: 'claude' });

    // ~/.teamai still exists (minimal uninstall was skipped)
    expect(await fse.pathExists(teamaiHome)).toBe(true);
  });

  it('目标工具无 teamai 资源 → no-op 不删共享', async () => {
    const { homeDir, repoPath, teamaiHome } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    // Strip all teamai resources from claude so it has zero teamai presence
    await fse.writeJson(path.join(homeDir, '.claude', 'settings.json'), {
      hooks: { SessionStart: [{ matcher: '*', hooks: [{ type: 'command', command: 'echo hi' }] }] },
    });
    await fse.remove(path.join(homeDir, '.claude', 'skills', 'team-skill'));
    await fse.remove(path.join(homeDir, '.claude', 'skills', 'teamai'));
    await fse.remove(path.join(homeDir, '.claude', 'skills', 'teamai-share-learnings'));
    await fse.remove(path.join(homeDir, '.claude', 'skills', 'team-wiki-codebase'));
    await fse.remove(path.join(homeDir, '.claude', 'rules', 'team-rule.md'));
    await fse.remove(path.join(homeDir, '.claude', 'rules', 'teamai-recall.md'));
    await fse.remove(path.join(homeDir, '.claude', 'agents', 'teamai-recall.md'));
    await fse.remove(path.join(homeDir, '.claude', 'CLAUDE.md'));

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'claude' });

    // ~/.teamai must still exist — target had no teamai resources
    expect(await fse.pathExists(teamaiHome)).toBe(true);
    expect(mockReconcileHooks).not.toHaveBeenCalled();
  });

  it('hooks 全为空数组时仍纳入清理范围（empty-array residue）', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    // Simulate a prior partial uninstall that left hooks cleared to empty arrays.
    await fse.writeJson(path.join(homeDir, '.claude', 'settings.json'), {
      hooks: { SessionStart: [], Stop: [], PostToolUse: [] },
    });

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    // reconcileHooks must be called — the file was recognised as having teamai residue.
    expect(mockReconcileHooks).toHaveBeenCalledWith(
      path.join(homeDir, '.claude', 'settings.json'),
      'claude',
      [],
      expect.objectContaining({ removeAll: true }),
    );
  });

  it('settings.json 无 hooks 字段时不纳入清理范围', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    // settings.json exists but has no hooks key at all — not a teamai file.
    await fse.writeJson(path.join(homeDir, '.claude', 'settings.json'), {
      model: 'claude-opus-4',
    });
    // Also remove all other teamai resources so nothing triggers cleanup.
    await fse.remove(path.join(homeDir, '.claude', 'skills', 'team-skill'));
    await fse.remove(path.join(homeDir, '.claude', 'skills', 'teamai'));
    await fse.remove(path.join(homeDir, '.claude', 'skills', 'teamai-share-learnings'));
    await fse.remove(path.join(homeDir, '.claude', 'skills', 'team-wiki-codebase'));
    await fse.remove(path.join(homeDir, '.claude', 'rules', 'team-rule.md'));
    await fse.remove(path.join(homeDir, '.claude', 'rules', 'teamai-recall.md'));
    await fse.remove(path.join(homeDir, '.claude', 'agents', 'teamai-recall.md'));
    await fse.remove(path.join(homeDir, '.claude', 'CLAUDE.md'));

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'claude' });

    // No hooks residue + no teamai resources → reconcileHooks not called.
    expect(mockReconcileHooks).not.toHaveBeenCalled();
  });

  it('hooks 有非空数组（用户自有 hook）时仅由 hasTeamaiHooks 判断是否纳入', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    // User has their own non-teamai hook — isEmptyHooksResidue must return false,
    // but hasTeamaiHooks will still detect the teamai hook that setupFixture added.
    await fse.writeJson(path.join(homeDir, '.claude', 'settings.json'), {
      hooks: {
        SessionStart: [{ matcher: '*', hooks: [{ type: 'command', command: 'teamai pull' }], description: '[teamai] Auto-pull' }],
        PostToolUse: [{ matcher: '*', hooks: [{ type: 'command', command: 'echo user-hook' }] }],
      },
    });

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    // hasTeamaiHooks detects the teamai hook → reconcileHooks must be called.
    expect(mockReconcileHooks).toHaveBeenCalledWith(
      path.join(homeDir, '.claude', 'settings.json'),
      'claude',
      [],
      expect.objectContaining({ removeAll: true }),
    );
  });

  it('--agent 大小写不敏感', async () => {
    const { homeDir, repoPath } = await setupFixture(tmpDir);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/zsh');

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true, agent: 'Claude' });

    // Should have matched 'claude' and removed team-skill
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'skills', 'team-skill'))).toBe(false);
  });

  it('仅含 teamai section 的 CLAUDE.md 被整文件删除', async () => {
    const homeDir = path.join(tmpDir, 'only-teamai-home');
    const repoPath = path.join(tmpDir, 'only-teamai-repo');
    await fse.ensureDir(repoPath);
    vi.stubEnv('HOME', homeDir);
    vi.stubEnv('SHELL', '/bin/bash');

    // CLAUDE.md with only teamai content (no user content)
    const onlyTeamaiMd = [
      TEAMAI_CULTURE_START,
      '## Culture',
      TEAMAI_CULTURE_END,
    ].join('\n');
    await fse.ensureDir(path.join(homeDir, '.claude'));
    await fse.writeFile(path.join(homeDir, '.claude', 'CLAUDE.md'), onlyTeamaiMd);

    const teamConfig = makeTeamConfig();
    const localConfig = makeLocalConfig(homeDir, repoPath);
    mockAutoDetectInit.mockResolvedValue({ localConfig, teamConfig });

    await uninstall({ force: true });

    // File should be deleted entirely when nothing remains
    expect(await fse.pathExists(path.join(homeDir, '.claude', 'CLAUDE.md'))).toBe(false);
  });
});
