/**
 * The `teamai-learnings` orphan branch: where `teamai contribute` publishes.
 *
 * Learnings leave the default branch so a member can contribute without write
 * access to a protected `main` (#485). Unlike reports, a learning is not
 * regenerated by the next session, so callers keep a durable copy until a
 * publish reports `published` — see `pending-learnings.ts`.
 */
import { createBranchWorktree } from './branch-worktree.js';
import {
  LEARNINGS_BRANCH,
  LEARNINGS_WORKTREE_DIRNAME,
  LEARNINGS_LOCK_FILENAME,
} from '../types.js';

export const learningsBranch = createBranchWorktree({
  branch: LEARNINGS_BRANCH,
  worktreeDirname: LEARNINGS_WORKTREE_DIRNAME,
  lockFilename: LEARNINGS_LOCK_FILENAME,
  logTag: 'learnings',
  initCommitMessage: '[teamai] Initialize learnings branch',
});
