/**
 * Hermes agent hook injection.
 *
 * Writes a bash status-report script under `<hermesHome>/hooks/` and
 * registers it in config.yaml `hooks:` plus the shell-hooks allowlist.
 * Provides symmetric inject / remove helpers and a generic per-agent-hook
 * apply / remove pair for use by the local-agent pipeline (wired in a later
 * batch).
 */

import path from 'node:path';
import { chmod } from 'node:fs/promises';
import { writeIfChanged, pathExists, remove } from './utils/fs.js';
import { log } from './utils/logger.js';
import { getHermesHome } from './hermes-home.js';
import {
  upsertHermesHook,
  removeHermesHookByCommand,
  addHermesAllowlist,
  removeHermesAllowlist,
} from './hermes-config.js';

/** Hermes hook event used for session-start status reporting. */
const REPORT_EVENT = 'on_session_start';

/** Absolute path to the generated status-report shell script. */
export function getReportScriptPath(): string {
  return path.join(getHermesHome(), 'hooks', 'teamai-status-report.sh');
}

/**
 * Return the content of the status-report shell script.
 * The script shells out to `teamai hook-dispatch` and swallows all errors so
 * it never blocks the agent session.
 */
function buildReportScript(): string {
  return [
    '#!/usr/bin/env bash',
    '# [teamai] status-report hook — generated by teamai, do not edit.',
    'teamai hook-dispatch session-start --tool hermes >/dev/null 2>&1 || true',
    '',
  ].join('\n');
}

/**
 * Inject (or refresh) the teamai Hermes status-report hook.
 *
 * Steps:
 * 1. Create the `hooks/` directory under the Hermes home.
 * 2. Write the shell script and mark it executable (0o755).
 * 3. Register the script in config.yaml `hooks.on_session_start`.
 * 4. Add the script path to the shell-hooks allowlist.
 */
export async function injectHermesHooks(): Promise<void> {
  const scriptPath = getReportScriptPath();
  const scriptChanged = await writeIfChanged(scriptPath, buildReportScript());
  try {
    await chmod(scriptPath, 0o755);
  } catch (e) {
    log.warn(`Failed to chmod Hermes hook script: ${(e as Error).message}`);
  }
  const hookChanged = await upsertHermesHook(REPORT_EVENT, { command: scriptPath, timeout: 60 });
  const allowlistChanged = await addHermesAllowlist(REPORT_EVENT, scriptPath);
  if (scriptChanged || hookChanged || allowlistChanged) {
    log.success('Injected teamai Hermes hook into ' + scriptPath);
  } else {
    log.debug(`teamai Hermes hook already up-to-date in ${scriptPath}`);
  }
}

/**
 * Remove the teamai Hermes status-report hook.
 *
 * Steps:
 * 1. Remove the script from config.yaml `hooks:`.
 * 2. Remove the script from the shell-hooks allowlist.
 * 3. Delete the script file if it exists.
 */
export async function removeHermesHooks(): Promise<void> {
  const scriptPath = getReportScriptPath();
  await removeHermesHookByCommand(scriptPath);
  await removeHermesAllowlist(REPORT_EVENT, scriptPath);
  if (await pathExists(scriptPath)) {
    await remove(scriptPath);
  }
  log.success('Removed teamai Hermes hook from ' + scriptPath);
}

/**
 * Register a named agent hook entry in Hermes config.yaml and allowlist.
 *
 * @param def - Hook definition including a human-readable `slug` for logging.
 */
export async function applyHermesAgentHook(def: {
  slug: string;
  event: string;
  command: string;
  matcher?: string;
  timeout?: number;
}): Promise<void> {
  const entry: { command: string; matcher?: string; timeout?: number } = {
    command: def.command,
  };
  if (def.matcher !== undefined) entry.matcher = def.matcher;
  if (def.timeout !== undefined) entry.timeout = def.timeout;

  await upsertHermesHook(def.event, entry);
  await addHermesAllowlist(def.event, def.command);
  log.success(`Installed Hermes agent hook [${def.slug}]`);
}

/**
 * Remove a named agent hook entry from Hermes config.yaml and allowlist.
 *
 * @param opts - At minimum `command` is required; providing `event` also
 *   removes the allowlist entry for that specific `(event, command)` pair.
 */
export async function removeHermesAgentHook(opts: {
  slug: string;
  event?: string;
  command: string;
}): Promise<void> {
  await removeHermesHookByCommand(opts.command);
  if (opts.event !== undefined) {
    await removeHermesAllowlist(opts.event, opts.command);
  }
  log.success(`Removed Hermes agent hook [${opts.slug}]`);
}
