/**
 * OpenCode hook injection.
 *
 * Unlike every other agent teamai targets, OpenCode has no settings.json-style
 * shell-command hook list. Instead it auto-loads JS/TS *plugins* — the config
 * loader scans `{plugin,plugins}/*.{ts,js}` under each `.opencode` dir (project
 * scope) and `~/.config/opencode` (user scope). A plugin is a module exporting a
 * function that returns a `Hooks` object; teamai subscribes to OpenCode's own
 * events and shells out to the same `teamai hook-dispatch` entry point every
 * other agent uses.
 *
 * Event mapping (OpenCode → teamai dispatch), chosen to mirror the Claude
 * built-in hook set as closely as OpenCode's event model allows:
 *   - `session.created`     → session-start  (report / sync / ack)
 *   - `session.idle`        → stop           (update / votes / contribute)
 *   - `chat.message`        → prompt-submit   (track-slash / dashboard)
 *   - `tool.execute.after`  → post-tool-use   (dashboard; matcher-scoped track)
 *
 * The generated plugin is fire-and-forget: OpenCode's `event` hook has no
 * channel to inject a hook's stdout back into the session, so — like the Hermes
 * and OpenClaw adapters — teamai runs the dispatch for its side effects and
 * never blocks the agent. Node's child-process errors are swallowed.
 */

import path from 'node:path';
import { writeFile, writeIfChanged, ensureDir, pathExists, remove } from './utils/fs.js';
import { log } from './utils/logger.js';

/** Plugin directory name under an OpenCode config dir. OpenCode scans both
 *  `plugin/` and `plugins/`; we use the singular, matching the docs examples. */
export const OPENCODE_PLUGIN_DIR = 'plugin';

/** Filename of the teamai-managed OpenCode plugin. */
export const OPENCODE_HOOK_FILE = 'teamai-hooks.ts';

/** Marker so `teamai doctor` / `uninstall` can recognize our generated plugin. */
const TEAMAI_MARKER = '[teamai]';

/**
 * Resolve the plugin directory for an OpenCode scope.
 *
 * - project scope: `<baseDir>/.opencode/plugin`
 * - user scope:    `<baseDir>/.config/opencode/plugin`
 *
 * (baseDir is the repo root in project scope and $HOME in user scope, matching
 * how teamai resolves every other OpenCode path.)
 */
export function resolveOpencodePluginDir(baseDir: string, scope: 'project' | 'user'): string {
  const configDir = scope === 'project' ? '.opencode' : path.join('.config', 'opencode');
  return path.join(baseDir, configDir, OPENCODE_PLUGIN_DIR);
}

/**
 * Build the teamai OpenCode plugin source.
 *
 * The plugin subscribes to OpenCode events and shells out to `teamai
 * hook-dispatch <event> --tool opencode [--matcher <m>]`, feeding the same JSON
 * payload on STDIN that every other agent's hooks send (`cwd`, `tool_name`,
 * `tool_input`, `prompt`). It uses Node's `child_process.spawn` with
 * `windowsHide: true` so a missing `teamai` binary or a non-zero exit never
 * surfaces as an error inside the agent session or opens a console window.
 *
 * Two OpenCode-specific bridges are required:
 *   - STDIN payload: hook-dispatch's track / track-slash / todowrite-hint
 *     handlers read `tool_name` / `tool_input` / `prompt` off STDIN, and the
 *     provider-config gate reads `cwd` to pick the project-scope config. Without
 *     a payload those handlers no-op and project gating falls back to the user
 *     config. We forward the plugin's `directory` as `cwd` plus the per-event
 *     fields.
 *   - Tool-id casing: OpenCode passes lowercase tool ids (`skill`, `todowrite`),
 *     but the handler registry keys matchers on Claude's PascalCase names
 *     (`Skill`, `TodoWrite`). We map the id back before dispatching a
 *     matcher-scoped pass.
 */
export function buildPluginSource(): string {
  return `// ${TEAMAI_MARKER} hooks plugin — generated by teamai, do not edit by hand.
//
// Bridges OpenCode's plugin events to \`teamai hook-dispatch\`, mirroring the
// Claude built-in hook set. Feeds the same STDIN JSON payload other agents send
// so the track / hint handlers and project-scope gating work. Errors are
// swallowed; OpenCode cannot inject a hook's stdout back into the session, so
// this runs the dispatch purely for its side effects (status report / sync /
// update).
//
// NOTE: OpenCode awaits its named hooks (chat.message, tool.execute.after), so
// the dispatch is not truly fire-and-forget for those two — see the timeout
// note below.

/** OpenCode lowercase tool ids → Claude PascalCase matcher names. */
const TOOL_MATCHER = { skill: 'Skill', todowrite: 'TodoWrite' };

/** @param {{ directory?: string, worktree?: string }} ctx */
export const TeamaiHooks = async ({ directory, worktree }) => {
  const cwd = directory || worktree;
  // Dispatch one hook event, forwarding a JSON payload on STDIN. \`payload\`
  // fields (cwd / tool_name / tool_input / prompt) match what hook-dispatch's
  // handlers read; \`matcher\` scopes PostToolUse handlers (Skill / TodoWrite).
  const dispatch = async (event, matcher, payload) => {
    try {
      const args = ['hook-dispatch', event, '--tool', 'opencode'];
      if (matcher) {
        args.push('--matcher', matcher);
      }
      const stdin = JSON.stringify({ cwd, ...(payload || {}) });
      const { spawn } = await import('node:child_process');
      await new Promise((resolve) => {
        const child = spawn('teamai', args, {
          shell: process.platform === 'win32',
          windowsHide: true,
          stdio: ['pipe', 'ignore', 'ignore'],
        });
        const finish = () => {
          child.removeListener('error', finish);
          child.removeListener('close', finish);
          resolve();
        };
        child.once('error', finish);
        child.once('close', finish);
        child.stdin.write(stdin);
        child.stdin.end();
      });
    } catch {
      // never block the agent
    }
  };

  return {
    event: async ({ event }) => {
      if (event.type === 'session.created') {
        await dispatch('session-start');
      } else if (event.type === 'session.idle') {
        await dispatch('stop');
      }
    },
    // A new user message maps to Claude's UserPromptSubmit. The prompt text
    // lives in output.parts (text parts); forward it so track-slash can see
    // slash-command usage.
    'chat.message': async (_input, output) => {
      let prompt = '';
      const parts = (output && output.parts) || [];
      for (const part of parts) {
        if (part && part.type === 'text' && typeof part.text === 'string') {
          prompt += part.text;
        }
      }
      await dispatch('prompt-submit', undefined, { prompt });
    },
    // Fires after every tool call. Dispatch the wildcard matcher always, plus a
    // matcher-scoped pass so Skill / TodoWrite handlers can fire. input.tool is
    // the lowercase OpenCode tool id; input.args is the tool input.
    'tool.execute.after': async (input) => {
      const tool = (input && input.tool) || '';
      const matcher = TOOL_MATCHER[tool];
      const payload = { tool_name: matcher || tool, tool_input: (input && input.args) || {} };
      await dispatch('post-tool-use', undefined, payload);
      if (matcher) {
        await dispatch('post-tool-use', matcher, payload);
      }
    },
  };
};
`;
}

/**
 * Inject (or refresh) the teamai OpenCode plugin for a scope.
 * Idempotent — writes and reports the plugin file only when its content changes.
 */
export async function injectOpencodeHooks(baseDir: string, scope: 'project' | 'user'): Promise<void> {
  const file = path.join(resolveOpencodePluginDir(baseDir, scope), OPENCODE_HOOK_FILE);
  if (await writeIfChanged(file, buildPluginSource())) {
    log.success(`Injected teamai OpenCode hook into ${file}`);
  } else {
    log.debug(`teamai OpenCode hook already up-to-date in ${file}`);
  }
}

/** Remove the teamai OpenCode plugin for a scope if present. */
export async function removeOpencodeHooks(baseDir: string, scope: 'project' | 'user'): Promise<void> {
  const dir = resolveOpencodePluginDir(baseDir, scope);
  const file = path.join(dir, OPENCODE_HOOK_FILE);
  if (await pathExists(file)) {
    await remove(file);
    log.success(`Removed teamai OpenCode hook from ${file}`);
  }
}

/**
 * Reject slugs that could escape the plugin directory when used as a filename.
 * Agent-hook slugs come from the backend command and are not otherwise
 * validated on the OpenCode path (skill / rule slugs go through validateSlug in
 * local-agent), so a slug like `../../evil` would write outside the plugin dir.
 */
function assertSafeSlug(slug: string): void {
  if (!slug || slug.includes('/') || slug.includes('\\') || slug.includes('..') || path.isAbsolute(slug)) {
    throw new Error(`Invalid agent-hook slug: ${slug}`);
  }
}

/** Map Claude PascalCase agent-hook events → OpenCode plugin event dispatch. */
const CLAUDE_TO_OPENCODE_EVENTS: Record<string, string> = {
  SessionStart: 'session.created',
  Stop: 'session.idle',
  UserPromptSubmit: 'chat.message',
  PostToolUse: 'tool.execute.after',
};

/**
 * Build an agent-hook plugin source that runs a fixed shell `command` on a
 * single OpenCode event. Used by the HTTP-source agent-hook pipeline (issue
 * #238) so an enterprise-pushed hook installs as a real OpenCode plugin rather
 * than silently landing in a Claude settings file OpenCode never reads.
 *
 * `matcher` scopes a `tool.execute.after` hook to a single tool (e.g. only run
 * after the Bash tool). OpenCode passes lowercase tool ids while matchers use
 * Claude's PascalCase names, so the generated gate compares case-insensitively.
 * A missing or `*` matcher runs on every tool call. For non-tool events the
 * matcher has no meaning and is ignored.
 */
export function buildAgentHookPluginSource(
  slug: string,
  ocEvent: string,
  command: string,
  matcher?: string,
): string {
  const scoped = ocEvent === 'tool.execute.after' && !!matcher && matcher !== '*';
  let body: string;
  if (ocEvent === 'tool.execute.after') {
    // Tool hook: optionally gate on the tool id (case-insensitive).
    body = scoped
      ? `  return {
    "tool.execute.after": async (input) => {
      const tool = (input && input.tool) || '';
      if (tool.toLowerCase() === ${JSON.stringify(matcher!.toLowerCase())}) { await run(); }
    },
  };`
      : `  return {
    "tool.execute.after": async () => { await run(); },
  };`;
  } else if (ocEvent === 'chat.message') {
    body = `  return {
    "chat.message": async () => { await run(); },
  };`;
  } else {
    // session.* events arrive via the generic `event` hook (event.type).
    body = `  return {
    event: async ({ event }) => {
      if (event.type === ${JSON.stringify(ocEvent)}) { await run(); }
    },
  };`;
  }
  return `// ${TEAMAI_MARKER} agent hook [${slug}] — generated by teamai, do not edit by hand.
/** @param {{ $: any }} ctx */
export const TeamaiAgentHook_${slug.replace(/[^A-Za-z0-9_]/g, '_')} = async ({ $ }) => {
  const run = async () => {
    try {
      // .quiet() suppresses output; .nothrow() keeps a non-zero exit from
      // throwing into the agent session. Fire-and-forget — never blocks.
      await $\`sh -c \${${JSON.stringify(command)}}\`.quiet().nothrow();
    } catch {
      // never block the agent
    }
  };
${body}
};
`;
}

/**
 * Install a server-pushed agent hook as an OpenCode plugin file.
 * Events with no OpenCode equivalent are logged and skipped.
 */
export async function applyOpencodeAgentHook(def: {
  slug: string;
  event: string;
  command: string;
  baseDir: string;
  scope: 'project' | 'user';
  matcher?: string;
}): Promise<void> {
  assertSafeSlug(def.slug);
  const ocEvent = CLAUDE_TO_OPENCODE_EVENTS[def.event];
  if (!ocEvent) {
    log.warn(`OpenCode does not support event "${def.event}" — skipping hook [${def.slug}]`);
    return;
  }
  const dir = resolveOpencodePluginDir(def.baseDir, def.scope);
  await ensureDir(dir);
  const file = path.join(dir, `teamai-agent-${def.slug}.ts`);
  await writeFile(file, buildAgentHookPluginSource(def.slug, ocEvent, def.command, def.matcher));
  log.success(`Installed OpenCode agent hook [${def.slug}] in ${file}`);
}

/** Remove a server-pushed agent-hook plugin file for OpenCode. */
export async function removeOpencodeAgentHook(opts: {
  slug: string;
  baseDir: string;
  scope: 'project' | 'user';
}): Promise<void> {
  assertSafeSlug(opts.slug);
  const dir = resolveOpencodePluginDir(opts.baseDir, opts.scope);
  const file = path.join(dir, `teamai-agent-${opts.slug}.ts`);
  if (await pathExists(file)) {
    await remove(file);
    log.success(`Removed OpenCode agent hook [${opts.slug}] from ${file}`);
  }
}
