/**
 * OpenClaw / 龙虾-family hook injection (issue #1, 方案二 §四).
 *
 * NOTE: WorkBuddy was originally assumed to use this OpenClaw engine, but
 * real-device verification (WorkBuddy 5.2.0) showed it embeds the CodeBuddy CLI
 * engine and reads Claude-format hooks from ~/.workbuddy/settings.json instead.
 * WorkBuddy is therefore wired via the settings-based path (see types.ts
 * toolPaths.workbuddy.settings), NOT here. This adapter remains for the other
 * claw variants (openclaw / qclaw / easyclaw / autoclaw) whose engine is still
 * unconfirmed; it writes a `HOOK.md` (frontmatter with metadata.openclaw.events)
 * plus a `handler.ts` under `<hooksDir>/<hookName>/`, both shelling out to the
 * same `teamai hook-dispatch` entry point.
 *
 * Hook directory resolution: honors OPENCLAW_STATE_DIR env var when set (e.g.
 * imate containers where the config dir is at /projects/.openclaw instead of
 * ~/.openclaw). Other claw variants fall back to ~/.<tool>.
 *
 * Events: `session:start` → session-start dispatch (report + sync);
 *         `command:new`   → prompt-submit dispatch (sync only).
 */

import path from 'node:path';
import { writeFile, ensureDir, pathExists, readFileSafe, remove } from './utils/fs.js';
import { log } from './utils/logger.js';

/**
 * Resolve the hooks directory for an OpenClaw-family tool.
 * Honors OPENCLAW_STATE_DIR env var when set (used when the config dir is relocated,
 * e.g. `/projects/.openclaw` in imate containers). Falls back to `~/.<tool>`.
 *
 * Currently only `openclaw` honors OPENCLAW_STATE_DIR. Other claw variants
 * (qclaw/easyclaw/autoclaw) are not confirmed to use the same env var and
 * always fall back to ~/.<tool>/hooks.
 */
export function resolveOpenClawHooksDir(tool: string): string {
  if (tool === 'openclaw' && process.env.OPENCLAW_STATE_DIR) {
    return path.join(process.env.OPENCLAW_STATE_DIR, 'hooks');
  }
  const home = process.env.HOME ?? '';
  return path.join(home, `.${tool}`, 'hooks');
}

/** Sub-directory name under <hooksDir> that holds the teamai OpenClaw hook. */
export const OPENCLAW_HOOK_DIR = 'teamai-status-report';

/** Marker so we can recognize (and cleanly remove) our own hook. */
const TEAMAI_MARKER = '[teamai]';

/** Map OpenClaw event → teamai dispatch event. */
const EVENT_MAP: Record<string, string> = {
  'session:start': 'session-start',
  'command:new': 'prompt-submit',
};

function buildHookMd(tool: string): string {
  const events = Object.keys(EVENT_MAP);
  const metadata = JSON.stringify({ openclaw: { events } });
  return [
    '---',
    `name: ${TEAMAI_MARKER} status-report`,
    `metadata:`,
    `  ${metadata}`,
    `handler: ./handler.ts`,
    '---',
    '',
    `${TEAMAI_MARKER} Reports agent status to the team backend (report/sync/ack) for tool \`${tool}\`.`,
    'Managed by teamai — do not edit by hand.',
    '',
  ].join('\n');
}

function buildHandlerTs(tool: string): string {
  // Map each OpenClaw event to the corresponding teamai dispatch event and shell
  // out. Failures are swallowed so the agent is never blocked.
  const mapLiteral = JSON.stringify(EVENT_MAP);
  return `// ${TEAMAI_MARKER} status-report handler — generated by teamai, do not edit.
import { spawn } from 'node:child_process';

const EVENT_MAP: Record<string, string> = ${mapLiteral};
const TOOL = ${JSON.stringify(tool)};

export default async function handler(ctx: { event?: string } = {}): Promise<void> {
  const dispatchEvent = ctx.event ? EVENT_MAP[ctx.event] : undefined;
  if (!dispatchEvent) return;
  try {
    const child = spawn('teamai', ['hook-dispatch', dispatchEvent, '--tool', TOOL], {
      stdio: ['inherit', 'ignore', 'ignore'],
    });
    child.on('error', () => {});
  } catch {
    // never block the agent
  }
}
`;
}

/**
 * Inject (or refresh) the teamai OpenClaw hook into `<hooksDir>`.
 * Idempotent — rewrites the two files each time.
 */
export async function injectOpenClawHooks(hooksDir: string, tool = 'openclaw'): Promise<void> {
  const effectiveHooksDir = resolveOpenClawHooksDir(tool);
  const dir = path.join(effectiveHooksDir, OPENCLAW_HOOK_DIR);
  await ensureDir(dir);
  await writeFile(path.join(dir, 'HOOK.md'), buildHookMd(tool));
  await writeFile(path.join(dir, 'handler.ts'), buildHandlerTs(tool));
  log.success(`Injected teamai OpenClaw hook into ${dir}`);
}

/** Remove the teamai OpenClaw hook from `<hooksDir>` if present. */
export async function removeOpenClawHooks(hooksDir: string): Promise<void> {
  const dir = path.join(hooksDir, OPENCLAW_HOOK_DIR);
  if (await pathExists(dir)) {
    await remove(dir);
    log.success(`Removed teamai OpenClaw hook from ${dir}`);
  }
  // Also check OPENCLAW_STATE_DIR in case the hook was installed there
  if (process.env.OPENCLAW_STATE_DIR) {
    const altDir = path.join(process.env.OPENCLAW_STATE_DIR, 'hooks', OPENCLAW_HOOK_DIR);
    if (altDir !== dir && await pathExists(altDir)) {
      await remove(altDir);
      log.success(`Removed teamai OpenClaw hook from ${altDir}`);
    }
  }
}

/** Map Claude PascalCase agent-hook events → OpenClaw colon-separated events. */
const CLAUDE_TO_OPENCLAW_EVENTS: Record<string, string> = {
  SessionStart: 'session:start',
  UserPromptSubmit: 'command:new',
};

function buildAgentHookMd(slug: string, openclawEvent: string): string {
  const metadata = JSON.stringify({ openclaw: { events: [openclawEvent] } });
  return [
    '---',
    `name: ${TEAMAI_MARKER} ${slug}`,
    `metadata:`,
    `  ${metadata}`,
    `handler: ./handler.ts`,
    '---',
    '',
    `${TEAMAI_MARKER} Agent hook [${slug}] — managed by teamai, do not edit by hand.`,
    '',
  ].join('\n');
}

function buildAgentHandlerTs(command: string, timeout: number): string {
  const timeoutMs = timeout * 1000;
  return [
    `// ${TEAMAI_MARKER} agent hook handler — generated by teamai, do not edit.`,
    `import { spawn } from 'node:child_process';`,
    '',
    `export default async function handler(): Promise<void> {`,
    '  try {',
    `    const child = spawn('sh', ['-c', ${JSON.stringify(command)}], {`,
    `      stdio: ['inherit', 'ignore', 'ignore'],`,
    `      timeout: ${timeoutMs},`,
    '    });',
    "    child.on('error', () => {});",
    '  } catch {',
    '    // never block the agent',
    '  }',
    '}',
    '',
  ].join('\n');
}

/**
 * Install a server-pushed agent hook as an OpenClaw hook directory.
 * Creates `~/<tool-root>/hooks/<slug>/HOOK.md + handler.ts`.
 * Events that have no OpenClaw equivalent are logged and skipped.
 */
export async function applyOpenClawAgentHook(def: {
  slug: string;
  event: string;
  command: string;
  tool?: string;
  matcher?: string;
  timeout?: number;
}): Promise<void> {
  const openclawEvent = CLAUDE_TO_OPENCLAW_EVENTS[def.event];
  if (!openclawEvent) {
    log.warn(`OpenClaw does not support event "${def.event}" — skipping hook [${def.slug}]`);
    return;
  }
  const tool = def.tool ?? 'openclaw';
  const hooksDir = resolveOpenClawHooksDir(tool);
  const dir = path.join(hooksDir, def.slug);
  await ensureDir(dir);
  await writeFile(path.join(dir, 'HOOK.md'), buildAgentHookMd(def.slug, openclawEvent));
  await writeFile(path.join(dir, 'handler.ts'), buildAgentHandlerTs(def.command, def.timeout ?? 10));
  log.success(`Installed OpenClaw agent hook [${def.slug}] in ${dir}`);
}

/**
 * Remove a server-pushed agent hook directory for an OpenClaw-family tool.
 */
export async function removeOpenClawAgentHook(opts: {
  slug: string;
  tool?: string;
}): Promise<void> {
  const tool = opts.tool ?? 'openclaw';
  const hooksDir = resolveOpenClawHooksDir(tool);
  const dir = path.join(hooksDir, opts.slug);
  if (await pathExists(dir)) {
    await remove(dir);
    log.success(`Removed OpenClaw agent hook [${opts.slug}] from ${dir}`);
  }
}

/**
 * Resolve the OpenClaw workspace directory by priority:
 * 1. Explicit workspacePath (server-sent)
 * 2. $OPENCLAW_STATE_DIR/openclaw.json → agents.defaults.workspace
 * 3. $HOME/.openclaw/workspace (default convention)
 *
 * Returns the first candidate whose directory exists, or null.
 */
export async function openclawWorkspaceCandidates(workspacePath?: string): Promise<string[]> {
  const candidates: string[] = [];
  if (workspacePath) candidates.push(workspacePath);
  const stateDir = process.env.OPENCLAW_STATE_DIR;
  if (stateDir && path.isAbsolute(stateDir)) {
    const cfgRaw = await readFileSafe(path.join(stateDir, 'openclaw.json'));
    if (cfgRaw) {
      try {
        const cfg = JSON.parse(cfgRaw);
        const ws = cfg?.agents?.defaults?.workspace;
        if (typeof ws === 'string' && ws) candidates.push(ws);
      } catch (e) { log.debug(`openclaw: failed to parse openclaw.json: ${(e as Error).message}`); }
    }
  }
  const home = process.env.HOME;
  if (home) candidates.push(path.join(home, '.openclaw', 'workspace'));
  return candidates;
}

export async function resolveOpenclawWorkspaceDir(workspacePath?: string): Promise<string | null> {
  const candidates = await openclawWorkspaceCandidates(workspacePath);
  for (const candidate of candidates) {
    if (await pathExists(candidate)) {
      log.debug(`openclaw: resolved workspace dir to ${candidate}`);
      return candidate;
    }
  }
  log.warn(`openclaw: no workspace dir found (tried: ${candidates.join(', ') || 'none'})`);
  return null;
}
