/**
 * Pi Coding Agent hook injection.
 *
 * Pi discovers TypeScript extensions from ~/.pi/agent/extensions and from a
 * project .pi/extensions directory, auto-loading both. Only ONE copy is ever
 * written, in the user agent dir — a project copy would double-dispatch every
 * lifecycle event (the same single-copy policy as the OMP adapter). A
 * TeamAI-marked project copy left by an earlier revision is removed during
 * the next sync of that project. Pi has no settings file for self mode to
 * commit, so a fresh clone still needs one `teamai init`/`pull` on that
 * machine before Pi hooks are active there. The extension always dispatches
 * — hook-dispatch has no per-project exclusion check for any tool, so a
 * single shared file has no way to skip a project that has excluded Pi; the
 * `cwd` on STDIN only lets downstream handlers resolve the right project
 * context, not opt a project out. A targeted removal (scoped `uninstall` or
 * `hooks remove`) therefore deletes this one global copy outright, same as
 * the OMP adapter. The extension bridges TeamAI's built-in lifecycle events
 * only; custom team hooks declared in hooks/hooks.yaml are outside this
 * adapter's current scope. Pi profile overrides (`PI_CODING_AGENT_DIR` /
 * `PI_CONFIG_DIR`), which relocate the agent directory, are not supported —
 * same as the OMP adapter — and the default `~/.pi/agent/` layout is used.
 */

import path from 'node:path';
import { writeFile, writeIfChanged, ensureDir, pathExists, remove, readFileSafe } from './utils/fs.js';
import { getUserHome } from './utils/home.js';
import { log } from './utils/logger.js';

/** Filename of the TeamAI-managed Pi extension. */
export const PI_HOOK_FILE = 'teamai-hooks.ts';

const TEAMAI_MARKER = '[teamai]';

const CLAUDE_TO_PI_EVENTS: Record<string, string> = {
  SessionStart: 'session_start',
  UserPromptSubmit: 'before_agent_start',
  PreToolUse: 'tool_execution_start',
  PostToolUse: 'tool_execution_end',
  Stop: 'agent_settled',
};

/** The global Pi agent extension directory. */
export function resolvePiExtensionsDir(): string {
  return path.join(getUserHome(), '.pi', 'agent', 'extensions');
}

/** Project-local Pi extension directory used only to clean up legacy copies. */
export function resolvePiProjectExtensionsDir(baseDir: string): string {
  return path.join(baseDir, '.pi', 'extensions');
}

/** Build the generated Pi extension source. */
export function buildPiExtensionSource(): string {
  return `// ${TEAMAI_MARKER} hooks extension — generated by teamai, do not edit by hand.
//
// Bridges Pi extension events to the shared teamai hook-dispatch entry
// point. The child process receives the same JSON payload as shell-based hooks
// (cwd / tool_name / tool_input / prompt). Errors and timeouts are swallowed so
// a missing teamai binary never blocks the Pi session.

import { spawn } from "node:child_process";

/** @param {any} pi Pi ExtensionAPI */
export default function teamaiHooks(pi) {
  const toolInputs = new Map();
  const dispatch = async (event, cwd, payload) => {
    try {
      const command = process.platform === "win32" ? "teamai.cmd" : "teamai";
      const args = ["hook-dispatch", event, "--tool", "pi"];
      const child = spawn(command, args, {
        cwd,
        stdio: ["pipe", "ignore", "ignore"],
        windowsHide: true,
        shell: process.platform === "win32",
      });
      const stdin = JSON.stringify({ cwd, ...(payload || {}) });
      child.stdin?.on("error", () => {});
      child.stdin?.end(stdin);
      await new Promise((resolve) => {
        let settled = false;
        const finish = () => {
          if (settled) return;
          settled = true;
          clearTimeout(timer);
          resolve(undefined);
        };
        const timer = setTimeout(() => {
          try { child.kill(); } catch {}
          finish();
        }, 15000);
        child.once("close", finish);
        child.once("error", finish);
      });
    } catch {
      // never block the agent
    }
  };

  pi.on("session_start", async (_event, ctx) => {
    await dispatch("session-start", ctx.cwd);
  });

  pi.on("agent_settled", async (_event, ctx) => {
    await dispatch("stop", ctx.cwd);
  });

  pi.on("before_agent_start", async (event, ctx) => {
    await dispatch("prompt-submit", ctx.cwd, { prompt: event.prompt });
  });

  pi.on("tool_execution_start", async (event) => {
    toolInputs.set(event.toolCallId, event.args);
  });

  pi.on("tool_execution_end", async (event, ctx) => {
    await dispatch("post-tool-use", ctx.cwd, {
      tool_name: event.toolName,
      tool_input: toolInputs.get(event.toolCallId) || {},
    });
    toolInputs.delete(event.toolCallId);
  });
}
`;
}

/**
 * Inject or refresh the single global TeamAI Pi extension. Mirrors the
 * ownership check `removePiHooks` already applies: a same-named file without
 * TeamAI's marker is left untouched rather than overwritten.
 */
export async function injectPiHooks(): Promise<void> {
  const dir = resolvePiExtensionsDir();
  const file = path.join(dir, PI_HOOK_FILE);
  if (await pathExists(file) && !await hasPiHooks()) {
    log.warn(`Skipping Pi hook injection: ${file} exists without the TeamAI marker`);
    return;
  }
  if (await writeIfChanged(file, buildPiExtensionSource())) {
    log.success(`Injected teamai Pi hook into ${file}`);
  } else {
    log.debug(`teamai Pi hook already up-to-date in ${file}`);
  }
}

/** Remove the generated global Pi extension if present. */
export async function removePiHooks(): Promise<void> {
  const file = path.join(resolvePiExtensionsDir(), PI_HOOK_FILE);
  if (!await hasPiHooks()) return;
  await remove(file);
  log.success(`Removed teamai Pi hook from ${file}`);
}

/** Remove a TeamAI-managed project copy written by an earlier revision. */
export async function removePiProjectHooks(baseDir: string): Promise<void> {
  const file = path.join(resolvePiProjectExtensionsDir(baseDir), PI_HOOK_FILE);
  if (!await hasPiHooks(baseDir)) return;
  await remove(file);
  log.success(`Removed legacy project Pi hook from ${file}`);
}

function assertSafeSlug(slug: string): void {
  if (!slug || slug.includes('/') || slug.includes('\\') || slug.includes('..') || path.isAbsolute(slug)) {
    throw new Error(`Invalid Pi agent-hook slug: ${slug}`);
  }
}

/** Build a Pi extension for one HTTP-source agent hook. */
export function buildPiAgentHookExtensionSource(
  slug: string,
  event: string,
  command: string,
  matcher?: string,
  timeout = 10,
): string {
  const piEvent = CLAUDE_TO_PI_EVENTS[event];
  if (!piEvent) return '';
  const toolEvent = piEvent === 'tool_execution_start' || piEvent === 'tool_execution_end';
  const matcherGate = toolEvent && matcher && matcher !== '*'
    ? piEvent === 'tool_execution_end'
      ? `\n    if (String(event.toolName || '').toLowerCase() !== ${JSON.stringify(matcher.toLowerCase())}) { toolInputs.delete(event.toolCallId); return; }`
      : `\n    if (String(event.toolName || '').toLowerCase() !== ${JSON.stringify(matcher.toLowerCase())}) return;`
    : '';
  const timeoutMs = Math.max(1, timeout) * 1000;
  const captureToolStart = piEvent === 'tool_execution_end'
    ? '  pi.on("tool_execution_start", async (event) => {\n    toolInputs.set(event.toolCallId, event.args || {});\n  });\n'
    : '';
  const payload = piEvent === 'before_agent_start'
    ? '{ prompt: event.prompt }'
    : piEvent === 'tool_execution_start'
      ? '{ tool_name: event.toolName, tool_input: event.args || {} }'
      : piEvent === 'tool_execution_end'
        ? '{ tool_name: event.toolName, tool_input: toolInputs.get(event.toolCallId) || {} }'
        : '{}';
  const cleanupToolInput = piEvent === 'tool_execution_end'
    ? '\n    toolInputs.delete(event.toolCallId);'
    : '';
  return `// ${TEAMAI_MARKER} agent hook [${slug}] — generated by teamai, do not edit by hand.\nimport { spawn } from "node:child_process";\n\nexport default function teamaiAgentHook(pi) {\n  const toolInputs = new Map();\n  const run = async (cwd, payload) => {\n    try {\n      const shell = process.platform === "win32" ? "cmd.exe" : "sh";\n      const args = process.platform === "win32" ? ["/d", "/s", "/c", ${JSON.stringify(command)}] : ["-c", ${JSON.stringify(command)}];\n      const child = spawn(shell, args, { cwd, stdio: ["pipe", "ignore", "ignore"], windowsHide: true });\n      child.stdin?.on("error", () => {});\n      child.stdin?.end(JSON.stringify({ cwd, ...(payload || {}) }));\n      await new Promise((resolve) => {\n        const timer = setTimeout(() => { try { child.kill(); } catch {} resolve(undefined); }, ${timeoutMs});\n        child.once("close", () => { clearTimeout(timer); resolve(undefined); });\n        child.once("error", () => { clearTimeout(timer); resolve(undefined); });\n      });\n    } catch {}\n  };\n${captureToolStart}  pi.on(${JSON.stringify(piEvent)}, async (event, ctx) => {${matcherGate}\n    await run(ctx.cwd, ${payload});${cleanupToolInput}\n  });\n}\n`;
}

/** Filename of one HTTP-source agent-hook extension, keyed by slug. */
function piAgentHookFile(slug: string): string {
  return path.join(resolvePiExtensionsDir(), `teamai-agent-${slug}.ts`);
}

/**
 * Check whether a specific `teamai-agent-<slug>.ts` file carries TeamAI's
 * per-slug marker. Mirrors `hasPiHooks` for the main extension — write/remove
 * on this file must never touch a same-named file a user authored by hand.
 */
export async function hasPiAgentHook(slug: string): Promise<boolean> {
  const content = await readFileSafe(piAgentHookFile(slug));
  return content?.includes(`${TEAMAI_MARKER} agent hook [${slug}]`) ?? false;
}

/**
 * Install one HTTP-source agent hook as a Pi extension.
 *
 * Throws instead of warn-and-skip on both the unsupported-event and
 * marker-collision cases: the caller (runHookRuleCommand) acks this back to
 * the server and writes the local manifest only after this resolves, so a
 * silent no-op here would leave both sides believing the hook is installed
 * when the file was never touched.
 */
export async function applyPiAgentHook(def: {
  slug: string;
  event: string;
  command: string;
  matcher?: string;
  timeout?: number;
}): Promise<void> {
  assertSafeSlug(def.slug);
  const source = buildPiAgentHookExtensionSource(def.slug, def.event, def.command, def.matcher, def.timeout);
  if (!source) {
    throw new Error(`Pi does not support event "${def.event}" — skipping hook [${def.slug}]`);
  }
  const file = piAgentHookFile(def.slug);
  if (await pathExists(file) && !await hasPiAgentHook(def.slug)) {
    throw new Error(`Skipping Pi agent hook [${def.slug}]: ${file} exists without the TeamAI marker`);
  }
  await ensureDir(resolvePiExtensionsDir());
  await writeFile(file, source);
  log.success(`Installed Pi agent hook [${def.slug}]`);
}

/** Remove one HTTP-source agent-hook extension. */
export async function removePiAgentHook(slug: string): Promise<void> {
  assertSafeSlug(slug);
  if (!await hasPiAgentHook(slug)) return;
  await remove(piAgentHookFile(slug));
  log.success(`Removed Pi agent hook [${slug}]`);
}

/** Check whether a global or legacy project extension has TeamAI's marker. */
export async function hasPiHooks(baseDir?: string): Promise<boolean> {
  const file = path.join(baseDir ? resolvePiProjectExtensionsDir(baseDir) : resolvePiExtensionsDir(), PI_HOOK_FILE);
  if (!await pathExists(file)) return false;
  const content = await readFileSafe(file);
  return content?.includes(`${TEAMAI_MARKER} hooks extension`) ?? false;
}
