// -*- coding: utf-8 -*-
/**
 * MR/PR comment 格式化与幂等发布。
 *
 * 支持 GitHub REST API 和 TGit REST API，通过 marker 锚点实现
 * 同一 MR 上多次运行只产生/更新一条 comment。
 */

import type { LearningDraft, CodebaseSuggestion } from '../types.js';
import { tgitFetch } from '../providers/tgit/rest-auth.js';
import { log } from '../utils/logger.js';

// ─── 常量 ────────────────────────────────────────────────

const DEFAULT_MARKER = '<!-- teamai:ci-extract -->';
const API_TIMEOUT_MS = 15_000;

// ─── 类型 ────────────────────────────────────────────────

export interface CommentResult {
  created: boolean;
  url?: string;
}

interface ParsedMrUrl {
  provider: 'github' | 'tgit';
  owner: string;
  repo: string;
  number: string;
}

// ─── URL 解析 ────────────────────────────────────────────

/**
 * 从 MR/PR URL 解析 provider + owner/repo + number。
 */
export function parseMrUrl(url: string): ParsedMrUrl {
  // GitHub: https://github.com/{owner}/{repo}/pull/{number}
  const ghMatch = url.match(/github\.com\/([^/]+)\/([^/]+)\/pull\/(\d+)/);
  if (ghMatch) {
    return { provider: 'github', owner: ghMatch[1], repo: ghMatch[2], number: ghMatch[3] };
  }

  // TGit: https://git.woa.com/{group}/{project}/merge_requests/{iid}
  // group 可能含多级路径
  const tgitMatch = url.match(/git\.woa\.com\/(.+)\/([^/]+)\/merge_requests\/(\d+)/);
  if (tgitMatch) {
    return { provider: 'tgit', owner: tgitMatch[1], repo: tgitMatch[2], number: tgitMatch[3] };
  }

  throw new Error(`无法解析 MR URL: ${url}，仅支持 GitHub 和 TGit`);
}

// ─── Comment 格式化 ──────────────────────────────────────

/**
 * 格式化 AI 提炼结果为 Markdown comment 内容。
 */
export function formatComment(
  learning: LearningDraft | undefined,
  suggestions: CodebaseSuggestion[] | undefined,
  marker: string,
): string {
  const lines: string[] = [marker, '', '## TeamAI 知识提炼', ''];

  if (learning) {
    lines.push('### Learning', '');
    lines.push(`**${learning.title}**`, '');
    lines.push('<details>', '<summary>展开完整内容</summary>', '');
    lines.push('```markdown');
    lines.push(learning.content);
    lines.push('```');
    lines.push('', '</details>', '');
  }

  if (suggestions && suggestions.length > 0) {
    lines.push('### Codebase.md 更新建议', '');
    lines.push('| 章节 | 操作 | 内容预览 |');
    lines.push('|------|------|---------|');
    for (const s of suggestions) {
      const preview = s.content.replace(/\n/g, ' ').slice(0, 80);
      lines.push(`| ${s.section} | ${s.action} | ${preview} |`);
    }
    lines.push('');
  }

  if (!learning && (!suggestions || suggestions.length === 0)) {
    lines.push('> 本次 MR 无可提炼的知识内容。', '');
  }

  lines.push('---');
  lines.push('> MR 合入后将自动应用以上建议到团队知识库。');
  lines.push('> _Auto-generated by `teamai ci extract-mr`_');

  return lines.join('\n');
}

// ─── GitHub Comment API ─────────────────────────────────

async function githubRequest(path: string, method: string, body?: unknown): Promise<Response> {
  const token = process.env['GITHUB_TOKEN'];
  if (!token) throw new Error('未设置 GITHUB_TOKEN 环境变量');

  const url = `https://api.github.com${path}`;
  const headers: Record<string, string> = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'User-Agent': 'teamai-cli',
  };
  if (body) headers['Content-Type'] = 'application/json';

  return fetch(url, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
    signal: AbortSignal.timeout(API_TIMEOUT_MS),
  });
}

interface GitHubComment {
  id: number;
  body: string;
  html_url: string;
}

async function findGitHubComment(
  owner: string,
  repo: string,
  prNumber: string,
  marker: string,
): Promise<GitHubComment | null> {
  const resp = await githubRequest(
    `/repos/${owner}/${repo}/issues/${prNumber}/comments?per_page=100`,
    'GET',
  );
  if (!resp.ok) {
    throw new Error(`GitHub comment list request failed (${resp.status})`);
  }
  const comments = (await resp.json()) as GitHubComment[];
  return comments.find((c) => c.body.includes(marker)) ?? null;
}

async function postGitHubComment(
  owner: string,
  repo: string,
  prNumber: string,
  body: string,
): Promise<CommentResult> {
  const resp = await githubRequest(
    `/repos/${owner}/${repo}/issues/${prNumber}/comments`,
    'POST',
    { body },
  );
  if (!resp.ok) {
    const errText = await resp.text();
    throw new Error(`GitHub comment 创建失败 (${resp.status}): ${errText}`);
  }
  const data = (await resp.json()) as GitHubComment;
  return { created: true, url: data.html_url };
}

async function updateGitHubComment(
  owner: string,
  repo: string,
  commentId: number,
  body: string,
): Promise<CommentResult> {
  const resp = await githubRequest(
    `/repos/${owner}/${repo}/issues/comments/${commentId}`,
    'PATCH',
    { body },
  );
  if (!resp.ok) {
    const errText = await resp.text();
    throw new Error(`GitHub comment 更新失败 (${resp.status}): ${errText}`);
  }
  const data = (await resp.json()) as GitHubComment;
  return { created: false, url: data.html_url };
}

// ─── TGit Comment API ───────────────────────────────────

async function tgitRequest(path: string, method: string, body?: unknown): Promise<Response> {
  return tgitFetch(path, {
    method,
    body: body ? JSON.stringify(body) : undefined,
  });
}

interface TGitNote {
  id: number;
  body: string;
}

interface TGitMRInfo {
  id: number;
  iid: number;
}

/**
 * TGit Notes API 使用 MR 的全局 id（而非项目内 iid），
 * 需要先查询 MR 列表获取全局 id。
 */
async function getMrGlobalId(projectId: string, mrIid: string): Promise<number> {
  const resp = await tgitRequest(
    `/projects/${projectId}/merge_requests?iid=${mrIid}`,
    'GET',
  );
  if (!resp.ok) {
    throw new Error(`TGit 查询 MR 失败 (${resp.status})`);
  }
  const mrs = (await resp.json()) as TGitMRInfo[];
  const mr = mrs.find((m) => String(m.iid) === mrIid);
  if (!mr) {
    throw new Error(`TGit MR !${mrIid} 不存在`);
  }
  return mr.id;
}

async function findTGitComment(
  projectId: string,
  mrGlobalId: number,
  marker: string,
): Promise<TGitNote | null> {
  const resp = await tgitRequest(
    `/projects/${projectId}/merge_requests/${mrGlobalId}/notes?per_page=100`,
    'GET',
  );
  if (!resp.ok) {
    throw new Error(`TGit note list request failed (${resp.status})`);
  }
  const notes = (await resp.json()) as TGitNote[];
  return notes.find((n) => n.body.includes(marker)) ?? null;
}

async function postTGitComment(
  projectId: string,
  mrGlobalId: number,
  body: string,
): Promise<CommentResult> {
  const resp = await tgitRequest(
    `/projects/${projectId}/merge_requests/${mrGlobalId}/notes`,
    'POST',
    { body },
  );
  if (!resp.ok) {
    const errText = await resp.text();
    throw new Error(`TGit comment 创建失败 (${resp.status}): ${errText}`);
  }
  return { created: true };
}

async function updateTGitComment(
  projectId: string,
  mrGlobalId: number,
  noteId: number,
  body: string,
): Promise<CommentResult> {
  const resp = await tgitRequest(
    `/projects/${projectId}/merge_requests/${mrGlobalId}/notes/${noteId}`,
    'PUT',
    { body },
  );
  if (!resp.ok) {
    const errText = await resp.text();
    throw new Error(`TGit comment 更新失败 (${resp.status}): ${errText}`);
  }
  return { created: false };
}

// ─── Public API ─────────────────────────────────────────

/**
 * 幂等地向 MR/PR 发布或更新知识提炼 comment。
 *
 * 通过 marker HTML 注释锚点实现幂等：
 * - 首次运行：创建新 comment
 * - 后续运行：更新已有 comment（同一 marker）
 *
 * @param mrUrl       MR/PR 完整 URL
 * @param learning    AI 提炼的 learning 草稿
 * @param suggestions AI 提炼的 codebase 更新建议
 * @param marker      幂等锚点字符串
 * @param dryRun      true 则不实际调 API
 * @returns           操作结果
 */
export async function postOrUpdateMrComment(
  mrUrl: string,
  learning: LearningDraft | undefined,
  suggestions: CodebaseSuggestion[] | undefined,
  marker?: string,
  dryRun?: boolean,
): Promise<CommentResult> {
  const effectiveMarker = marker ?? DEFAULT_MARKER;
  const body = formatComment(learning, suggestions, effectiveMarker);
  const parsed = parseMrUrl(mrUrl);

  if (dryRun) {
    log.info('dry-run: 以下为将发布的 comment 内容:');
    console.log(body);
    return { created: true };
  }

  if (parsed.provider === 'github') {
    const existing = await findGitHubComment(
      parsed.owner,
      parsed.repo,
      parsed.number,
      effectiveMarker,
    );
    if (existing) {
      log.debug(`发现已有 comment #${existing.id}，更新中...`);
      return updateGitHubComment(parsed.owner, parsed.repo, existing.id, body);
    }
    return postGitHubComment(parsed.owner, parsed.repo, parsed.number, body);
  }

  // TGit — Notes API 使用 MR 全局 id
  const projectId = encodeURIComponent(`${parsed.owner}/${parsed.repo}`);
  const mrGlobalId = await getMrGlobalId(projectId, parsed.number);
  const existing = await findTGitComment(projectId, mrGlobalId, effectiveMarker);
  if (existing) {
    log.debug(`发现已有 note #${existing.id}，更新中...`);
    return updateTGitComment(projectId, mrGlobalId, existing.id, body);
  }
  return postTGitComment(projectId, mrGlobalId, body);
}

// ─── 逐条发布（Individual Comments）─────────────────────

/**
 * 格式化单条建议为独立 comment 内容。
 */
export function formatIndividualComment(
  type: 'learning' | 'suggestion',
  index: number,
  content: { title?: string; body?: string; section?: string; action?: string; preview?: string },
  provider: 'github' | 'tgit',
): string {
  const markerId = type === 'learning' ? 'learning' : `suggestion:${index}`;
  const marker = `<!-- teamai:ci-extract:${markerId} -->`;

  const lines: string[] = [marker, ''];

  if (type === 'learning') {
    lines.push(`## TeamAI Learning`, '');
    lines.push(`**${content.title}**`, '');
    if (content.body) {
      lines.push('<details>', '<summary>展开完整内容</summary>', '');
      lines.push('```markdown');
      lines.push(content.body);
      lines.push('```');
      lines.push('', '</details>');
    }
  } else {
    lines.push(`## TeamAI Codebase 建议 #${index}`, '');
    lines.push(`**章节**: ${content.section} | **操作**: ${content.action}`, '');
    if (content.preview) {
      lines.push('```');
      lines.push(content.preview.slice(0, 300));
      lines.push('```');
    }
  }

  lines.push('');
  if (provider === 'github') {
    lines.push('> 💡 不写入此条？请对本条 comment 加 👎 reaction');
  } else {
    lines.push('> 💡 不写入此条？请对本条评论加 ☝️ emoji reaction');
  }
  lines.push('');
  lines.push('_Auto-generated by `teamai ci extract-mr`_');

  return lines.join('\n');
}

/**
 * 逐条发布 learning 和 suggestions 为独立的 comment/note。
 *
 * 每条建议带唯一 marker，支持后续 readRejections 读取状态。
 * TGit 上发布为 conversation note，reviewer 通过 ☝️ emoji reaction 来 reject。
 */
export async function postIndividualComments(
  mrUrl: string,
  learning: LearningDraft | undefined,
  suggestions: CodebaseSuggestion[] | undefined,
  dryRun?: boolean,
): Promise<{ posted: number }> {
  const parsed = parseMrUrl(mrUrl);
  let posted = 0;

  const items: Array<{ markerId: string; body: string }> = [];

  // Learning
  if (learning) {
    const body = formatIndividualComment(
      'learning', 0,
      { title: learning.title, body: learning.content },
      parsed.provider,
    );
    items.push({ markerId: 'learning', body });
  }

  // Suggestions
  if (suggestions) {
    for (let i = 0; i < suggestions.length; i++) {
      const s = suggestions[i];
      const body = formatIndividualComment(
        'suggestion', i + 1,
        { section: s.section, action: s.action, preview: s.content },
        parsed.provider,
      );
      items.push({ markerId: `suggestion:${i + 1}`, body });
    }
  }

  if (items.length === 0) return { posted: 0 };

  if (dryRun) {
    for (const item of items) {
      log.info(`dry-run [${item.markerId}]:`);
      console.log(item.body);
      console.log('---');
    }
    return { posted: items.length };
  }

  if (parsed.provider === 'github') {
    for (const item of items) {
      const marker = `<!-- teamai:ci-extract:${item.markerId} -->`;
      const existing = await findGitHubComment(parsed.owner, parsed.repo, parsed.number, marker);
      if (existing) {
        await updateGitHubComment(parsed.owner, parsed.repo, existing.id, item.body);
      } else {
        await postGitHubComment(parsed.owner, parsed.repo, parsed.number, item.body);
      }
      posted++;
    }
  } else {
    // TGit: 作为 code review comment（关联文件），带 resolve 按钮
    const projectId = encodeURIComponent(`${parsed.owner}/${parsed.repo}`);
    const mrGlobalId = await getMrGlobalId(projectId, parsed.number);

    // 获取 MR 变更文件列表，取第一个文件作为 code review comment 锚点
    // 使用 /repository/compare API（/changes 对某些 MR 状态不可用）
    const mrListResp = await tgitRequest(
      `/projects/${projectId}/merge_requests?iid=${parsed.number}`,
      'GET',
    );
    let anchorFile = 'README.md';
    if (mrListResp.ok) {
      const mrList = (await mrListResp.json()) as Array<{ source_branch: string; target_branch: string }>;
      if (mrList.length > 0) {
        const { source_branch, target_branch } = mrList[0];
        const compareResp = await tgitRequest(
          `/projects/${projectId}/repository/compare?from=${target_branch}&to=${source_branch}`,
          'GET',
        );
        if (compareResp.ok) {
          const compareData = (await compareResp.json()) as { diffs?: Array<{ new_path: string }> };
          if (compareData.diffs && compareData.diffs.length > 0) {
            anchorFile = compareData.diffs[0].new_path;
          }
        }
      }
    }

    for (const item of items) {
      const marker = `<!-- teamai:ci-extract:${item.markerId} -->`;
      // 检查是否已存在
      const existingNote = await findTGitComment(projectId, mrGlobalId, marker);
      if (existingNote) {
        await updateTGitComment(projectId, mrGlobalId, existingNote.id, item.body);
      } else {
        // 创建 code review comment（关联到文件第 1 行）
        const resp = await tgitRequest(
          `/projects/${projectId}/merge_requests/${mrGlobalId}/notes`,
          'POST',
          { body: item.body, path: anchorFile, line: 1, line_type: 'new' },
        );
        if (!resp.ok) {
          // fallback: 创建普通 note
          await postTGitComment(projectId, mrGlobalId, item.body);
        }
      }
      posted++;
    }
  }

  log.success(`已发布 ${posted} 条独立建议`);
  return { posted };
}

// ─── Codebase Graph Change Comment ──────────────────────

const CODEBASE_GRAPH_MARKER = '<!-- teamai:ci-extract:codebase-graph -->';

function formatGraphComment(summary: { added: string[]; removed: string[]; wikiUpdatePreview?: string }): string {
  const lines: string[] = [];
  lines.push('## 📊 Codebase 知识图谱变更');
  lines.push('');
  lines.push('本次 MR 触发了以下代码知识更新：');
  lines.push('');

  if (summary.added.length > 0) {
    lines.push(`### 新增节点 (${summary.added.length})`);
    for (const item of summary.added.slice(0, 20)) {
      lines.push(`- ${item}`);
    }
    if (summary.added.length > 20) {
      lines.push(`- _...及另外 ${summary.added.length - 20} 项_`);
    }
    lines.push('');
  }

  if (summary.removed.length > 0) {
    lines.push(`### 删除节点 (${summary.removed.length})`);
    for (const item of summary.removed.slice(0, 10)) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  if (summary.wikiUpdatePreview) {
    lines.push(summary.wikiUpdatePreview);
    lines.push('');
  }

  lines.push('---');
  lines.push('> 👎 对本条 comment 添加 reaction 将阻止本次图谱更新写入团队知识库');
  lines.push(CODEBASE_GRAPH_MARKER);
  return lines.join('\n');
}

export async function postCodebaseGraphComment(
  mrUrl: string,
  summary: { added: string[]; removed: string[]; wikiUpdatePreview?: string },
  dryRun?: boolean,
): Promise<void> {
  const body = formatGraphComment(summary);
  const parsed = parseMrUrl(mrUrl);

  if (dryRun) {
    log.info('[dry-run] Codebase graph comment:');
    console.log(body);
    return;
  }

  if (parsed.provider === 'github') {
    const existing = await findGitHubComment(parsed.owner, parsed.repo, parsed.number, CODEBASE_GRAPH_MARKER);
    if (existing) {
      await updateGitHubComment(parsed.owner, parsed.repo, existing.id, body);
    } else {
      await postGitHubComment(parsed.owner, parsed.repo, parsed.number, body);
    }
  } else {
    const projectId = encodeURIComponent(`${parsed.owner}/${parsed.repo}`);
    const mrGlobalId = await getMrGlobalId(projectId, parsed.number);
    const existing = await findTGitComment(projectId, mrGlobalId, CODEBASE_GRAPH_MARKER);
    if (existing) {
      await updateTGitComment(projectId, mrGlobalId, existing.id, body);
    } else {
      await postTGitComment(projectId, mrGlobalId, body);
    }
  }
  log.success('Codebase 图谱变更 comment 已发布');
}
